### PR TITLE
rds and rds cluster changes- issue 1091

### PR DESCRIPTION
**Pull request by arunakalla**
the current rds retention policy action, will take the larger of desired days vs current instance backup days. when setting a new standard policy thats smaller, its desirable to have an option such that it takes the policy configured days without consideration of current.

### CODE REVIEW

**Comment by kapilt** [comment]
i think we want to preserve both scenarios by enabling this behavior on via action parameter, their both valid use cases, setting a minimum default, and changing the current on the fleet.

**Comment by kapilt** [comment]
there's a few syntax errors in this pr at the moment

**Comment by arunakalla** [comment]
lets say if we create another action item retention-new and give provision to modify backup retention period to a value between 1 and 35 regardless of current value, people always use this, instead of the current retention action which considers only higher value than the current_retention?.

**Comment by arunakalla** [comment]
action retention retained and
added new action retention1to35, which updates BackupRetentionPeriod to a value between 1 and 35

**Comment by kapilt** [comment]
I'm confused why this is a separate action rather than parameters to the original retention actions.

**Comment by arunakalla** [comment]
as suggested I have added days1to35 parameter for retention action..

**Pull request closed without merging**
