### PR TITLE
adding & correcting docstring examples to iam.py

### PR DESCRIPTION
**Pull request by joshuaroot**
- correcting examples for a few existing functions
- adding new examples for functions that were missing
- all examples have been tests & verified

### CODE REVIEW

**Comment by joshuaroot** [comment]
my attempts to rebase this seem to be just generating more commit lines. :(

**Comment by kapilt** [comment]
thanks for working at correcting these doc strings, it might be worthwhile to do a systemic review of the doc strings examples you added last year, many folks have corrected examples across other modules, as most of them didn't work, i think we're on the tail end of fixing all of them, but it would be good to verify. There is actually a python doc test module we could try out. wrt to the merge, there was a release to upstream sphinx which caused some doc issues, i've resolved that on trunk.

**Comment by kapilt** [comment]
there's a separate thought that most of these boolean style pair filters (used/unused) are deprecated elsewhere for a single filter that can do both via parameterization, also note there's a bug in unused wrt to checking instance profiles.

**Comment by joshuaroot** [comment]
I was planning on going through each of the modules and the related doc strings to correct anything that is still not correct.

**Comment by joshuaroot** [comment]
Also, I think I see where the disconnect is with the instance profile roles... should I put that in a seperate PR from this?

**Comment by kapilt** [comment]
separate pr definitely, this one is fine as is, there's a separate issue open on the instance profile, thanks for doing the doc string review.

**Pull request merged**
