### PR TITLE
Fix functional tests, part 2

### PR DESCRIPTION
**Pull request by whit537**
Builds on https://github.com/capitalone/cloud-custodian/pull/1729, for https://github.com/capitalone/cloud-custodian/issues/903.

### CODE REVIEW

**Comment by whit537** [comment]
Rebased, was 74a6ca9c794fb18086d7577361020f376d9c75c6.

**Comment by whit537** [comment]
Per call, new goal is to get this passing (non-functional) CI w/ a write-up about status of functional tests.

**Comment by whit537** [comment]
Functional run with 0e4031a0d15f671668af2dde99feda8287465c4b:

```
C7N_FUNCTIONAL=yes AWS_DEFAULT_REGION=us-east-2 py.test -m functional tests
============================= test session starts ==============================
platform darwin -- Python 2.7.13, pytest-3.2.5, py-1.5.2, pluggy-0.4.0
rootdir: /Users/whit537/workbench/capitalone/cloud-custodian, inifile: tox.ini
plugins: xdist-1.20.1, forked-0.2, cov-2.5.1
collected 824 items

tests/test_account.py .
tests/test_datapipeline.py ....
tests/test_ecr.py ...
tests/test_efs.py .
tests/test_glacier.py ....
tests/test_iam.py F
tests/test_kms.py .F
tests/test_lambda.py ..
tests/test_notify.py .F
tests/test_rdsparamgroup.py ......
tests/test_s3.py ....F..
tests/test_sns.py ..
tests/test_sqs.py ..FF..F.
tests/test_vpc.py ...............
```

Looking at non-functional failures ...

**Comment by whit537** [comment]
Rerecorded, fixed one. Working on second ...

**Comment by scotwk** [comment]
@whit537 - you can see my work on SQS here: f96fe6ee81dc639e75beb0f154255ac8807be961

It solves the first issue of the queues being named the same.  It does not yet solve the issue where the code bombs out because it claims the queue does not exist.  (Also, once it works then all SQS tests probably need to be re-recorded)

**Comment by whit537** [comment]
Closing in favor of https://github.com/capitalone/cloud-custodian/pull/1923.

**Pull request closed without merging**
