### PR TITLE
Adding dms-endpoint delete action and usecase examples

### PR DESCRIPTION
**Pull request by jtroberts83**
For better SSL enforcement on dms endpoints I have added a delete action and tests as well as a couple usecase examples on dms-endpoint SSL

### CODE REVIEW

**Comment by jtroberts83** [comment]
@kapilt Done with this PR if you can review and merge please.  Thanks

**Comment by kapilt** [comment]
Docs and action look great, the test needs an additional check, its not actually verifying the delete, ie. if you replaced the action implementation with a `pass` the test would still pass. Typically we would construct a dms client and then verify that the endpoint no longer exists to verify the delete.

**Comment by jtroberts83** [comment]
ok I will look at checking once the dms endpoint is deleted.  Do you have to do a sleep after the delete for it to verify or how would you seperate the 2 tests so DMS has enough time to complete the deletion before the next test checks?

**Comment by jtroberts83** [comment]
ok I added a test after the delete to do a describe on the particular endpoint and make sure it's in a `deleting` status.  Will that satisfy the tests?

**Comment by jtroberts83** [comment]
@kapilt ok think it's ready again

**Pull request merged**
