### PR TITLE
flake8 for the entire repo

### PR DESCRIPTION
**Pull request by JohnTheodore**
This change has flake8 run on the entire repository. It excludes init py files since there is some weird importing techniques going on in there, it also excludes docs and tests directories.

There are no changes to how the code runs in this PR. It removes imports that were never used, or removes variables that were assigned but not used, lots of white space stuff, etc.

### CODE REVIEW

**Comment by kapilt** [comment]
thanks, given the current backlog of pull requests, i don't think its something we can merge at the moment without causing some conflicts on extant pull requests. instead it would be nice to just have this pull request as just a makefile target using yapf/autopep8 and adding those to requirements-dev.txt. if we drawn down on the extant pull requests, we can merge the cleanups, and as a next step do this as a git hook.

**Comment by JohnTheodore** [comment]
So yapf (from Google) just does formatting, and not pep8 or linting. There are no code changes from yapf in this PR. That PR would be multiple orders of magnitude larger than this one. I have no intent on making a yapf PR. I think yapf is not worth the tradeoff, and has a lot of downsides. I wouldn't want to include yapf in a make file for the dev pipeline either, since that causes others problems with code reviews and attribution in the future. also a yapf PR would be too massive to code review (it would basically change every file/line everywhere).

This PR is only for passing pep8/linting. I estimate this flake8 PR is <20 minutes to code review. I did use autopep8 to do part of this PR. Since autopep8 is conservative and won't make certain changes without breaking things, I probably fixed 70 or so things manually myself. So there is no way to automate this process (since I manually did a lot of it). This means that it can't exactly be included in a makefile. and as this PR ages, it will drift and the work would have to be done over again.

I think flake8 is worth it, you get some minimum cleanliness/linting of the codebase. ( no imports without using them, don't assign variables without using them, max line length, some styling enforcement (but minimal relative to yapf). If there are parts of pep8 folks don't want to deal with, it's easy to exclude those in the tox.ini file. I think there could be a couple conflicts, but not a lot, and it should be easy enough for folks to resolve those. Since this PR only touches a small fraction of 1% of the codebase, it's not very likely that other PRs touched the same lines I'm touching. Having said this, I'm ok if you don't think flake8 is worth it and don't want to merge this.

**Comment by JohnTheodore** [comment]
also if you checkout this branch, and do git diff master -w, git will ignore white space changes at the beginning/end of lines. that reduces 80% of the code review work.

**Comment by kapilt** [comment]
if you can update this, i think we're ready to merge it, re draw down on backlog prs.

**Comment by kapilt** [comment]
i tried the web based edit to resolve the conflict, and it seemed to do the trick.

**Comment by JohnTheodore** [comment]
updated and synced with the latest upstream changes

**Pull request merged**
