### PR TITLE
Add envvar and test helper for record vs. replay

### PR DESCRIPTION
**Pull request by whit537**
Factored out of #1084 for use elsewhere (e.g. https://github.com/whit537/cloud-custodian/pull/40#issuecomment-327733347).

### CODE REVIEW

**Comment by kapilt** [comment]
so your setting an env var and running a single test? re-recording enmasse seems like a disaster which is what would happen if someone blindly executes the tests in record against a live env. For folks not experienced with their respective test runner, i'd rather not include setting env vars into the dev workflow, experience has shown them to be a bit hard to discover and error prone. 

The functional tests do (make ftests) do effectively run live decorated tests but thats a fairly explicit entry point and intent.

The workflow comparison to swapping record/replay isn't clear to me on the delta value. Do you have an example scenario where the existing workflow is a burden? Is it a question of better dev docs?

**Comment by whit537** [comment]
I see what you mean about global re-record. Could extend to `C7N_RECORD=test_name_to_record`?

The main friction I'm trying to avoid is complicated state change from replay to record and back during dev workflow:

1. Write the test to use `replay_flight_data` + other variable behavior (`time.sleep`, etc.)
1. Git commit.
1. Update all calls to `replay_flight_data` to use `record_flight_data` instead + all other behavior variants (`#time.sleep()` throughout `test_s3.py` especially)
1. Run the test.
1. Update the calls back to `replay_flight_data` + other code variants.
1. Git commit.

I notice that we added a simpler version of `self.recording` on #1500. That works for simple cases, let me see what I can do with that for the class setup/teardown case on #1084.

**Comment by kapilt** [comment]
time.sleep should be conditional on whether the test is in recording mode, so that it works when doing functional test execution

**Comment by whit537** [comment]
> i don't generally commit to the end.

Right, but then imagine what happens when someone \*ahem\* reviews your work. ;-)

> time.sleep should be conditional on whether the test is in recording mode

Ya but until #1500 it was _manually_ conditional via commenting-out.

```
$ ack time\\.sleep
tests/test_efs.py
33:            time.sleep(5)

tests/test_log.py
57:        time.sleep(0.2)

tests/test_mu.py
130:        #time.sleep(15) -- turn this back on when recording flight data

tests/test_s3.py
944:        #time.sleep(10)
965:        #time.sleep(10)
993:        #time.sleep(10)
1014:        #time.sleep(10)
1253:        #time.sleep(10)
1266:        #time.sleep(30)
1307:        #time.sleep(10)
1317:        #time.sleep(30)
1383:        #time.sleep(10)
1393:        #time.sleep(30)
1455:        #time.sleep(10)
1465:        #time.sleep(30)
```

**Comment by whit537** [comment]
Alright, `time.sleep`s uncommented in e3dcec64e70da9931bcc32760596e0db8386753e.

-------------

4a1580f45193028f1fb36372b847c41b37523a5c and e4b624a144b1688d9a988ebfc89f91f08134af68 switch us from:

```python
session_factory = self.record_flight_data('test_foo_bar')
```

to:

```python
session_factory = self.get_session_factory('test_foo_bar', record=True)
```

That way we have a place to hook in a `C7N_RECORD` envvar that controls both class-level and method-level test fixture behavior. We can leave the envvar undocumented to avoid a footgun if you like, normal workflow (i.e., change via code) still remains.

If class-level fixture itself is questionable then we'll have to rework https://github.com/capitalone/cloud-custodian/pull/1084.

**Comment by whit537** [comment]
Rebased, was e4b624a144b1688d9a988ebfc89f91f08134af68.

**Comment by whit537** [comment]
Per #903, another reason to have an envvar for this is to support running all tests against live AWS.

**Comment by whit537** [comment]
Though I guess I need to wrap my head around what we're doing with `C7N_FUNCTIONAL` now ...

https://github.com/capitalone/cloud-custodian/blob/948170cbf03570af6f4494964ae10f09ed0028f8/tests/zpill.py#L274-L276

**Comment by kapilt** [comment]
see make ftests -> it runs all the functional decorated tests and just returns a live session from the replay. it should also probably be doing self.recording = True. but effectively the tests being run there have been explicitly marked as being functional. note there is no recorded output, its not a placebo wrapped session just a regular boto3 session.

**Pull request closed without merging**
