### PR TITLE
Add iam-role filters to check presence of specific managed policy

### PR DESCRIPTION
**Pull request by marchen87**
For situations where all managed roles must have specific policy attached or highlighting usage of highly critical managed policy (eg. FullAdministrator)

### CODE REVIEW

**Comment by kapilt** [comment]
Thanks! looks like travis failed when running sphinx on the doc strings of these filters.

**Comment by marchen87** [comment]
Great, just fixed that up!

**Comment by kapilt** [comment]
thanks @marchen87 before i can merge, would you mind signing our contributor license agreement referenced from our readme, direct link https://docs.google.com/forms/d/19LpBBjykHPox18vrZvBbZUcK6gQTj7qv1O5hCduAZFU/viewform

**Comment by marchen87** [comment]
@kapilt done, please go ahead

**Pull request merged**
