### PR TITLE
Fix the error message for duplicate policies (#1601)

### PR DESCRIPTION
**Pull request by scotwk**
#1601 

@kapilt - Oddly, this code path hadn't been touched in a long time.  I think we have a few different validation points in the code, but iirc they are hard to merge.  I made the simplest fix I could (I made the return value from `schema.py:validate()` more consistent).

### CODE REVIEW

**Comment by ewbankkit** [comment]
@scotwk Won't [this code](https://github.com/capitalone/cloud-custodian/blob/master/c7n/schema.py#L72-L75) also cause the same `IndexError: list index out of range` error?

**Comment by ewbankkit** [comment]
I've convinced myself that that fallthru bit of code should be OK.

**Comment by kapilt** [comment]
its rather unclear how this fixes the referenced issue, its just adding handling to the extant happy path that was already catching this issue.

**Comment by kapilt** [comment]
ah. its more clear now the error interface is expecting a tuple of (error, policy_name) which this corrects the dupe detection to.

**Pull request merged**
