### PR TITLE
add config_type to additional resources

### PR DESCRIPTION
**Pull request by r0fls**
Fix https://github.com/capitalone/cloud-custodian/issues/1319. Still working on adding a few more over the next half hour or so...

### CODE REVIEW

**Comment by r0fls** [comment]
after adding these types the lambda deployment from #1319 is deploying, however it's not firing when the resource is created. What iam role permissions are needed? It's not clear from the docs http://www.capitalone.io/cloud-custodian/docs/policy/lambda.html#config-rules:
>First, modify custodian.yml to specify a mode type of config-rule. You’ll also need the ARN of an IAM role to assume when running the Lambda that Custodian is going to install for you.

**Comment by kapilt** [comment]
so there's a few resources being added in this pull request which are not supported by aws config. if config doesn't support a resource type, custodian can't create an aws config rule for it. you can however create lambda policies for those resources which use cloudwatch events via cloudtrail policy mode.

http://docs.aws.amazon.com/config/latest/developerguide/resource-config-reference.html

**Comment by r0fls** [comment]
@kapilt let me know if you have something else in mind for the error.

**Comment by r0fls** [comment]
hmm the ci drone doesn't seem to like ammended commits :/ seems to be using one that was squashed into the above

**Comment by kapilt** [comment]
re-running on drone resolved, we had some ci churn for the last week, stabilized now.

**Comment by kapilt** [comment]
so the right place to do this would be as a validate method on the policy execution mode for config rule, which will basically cause a validation error before any policies are executed. as is the way its currently structured you'll get an error at runtime in the middle of policy execution. having it in both places sounds good. re validate method, here's an example on a cloud trail execution mode, adding something similiar to this pr diff to the config rule execution mode would suffice.
https://github.com/capitalone/cloud-custodian/blob/master/c7n/policy.py#L500

**Comment by kapilt** [comment]
perfect is not the enemy of the good, rolling with this and filing an issue re handle during validation. thanks.

**Pull request merged**
