### PR TITLE
count ValueType filter

### PR DESCRIPTION
**Pull request by scotwk**
No tests yet - will add this week.

Issue #342

### CODE REVIEW

**Comment by kapilt** [comment]
i had thought about having this directly on value filter as a value_type: count and handle it in that class's process method. mostly thats just preference for not having another generic filter but this implementation looks pretty good and simple, so let's roll with it as a separate count filter. +1

**Comment by kapilt** [comment]
note you'll need to update some of the permission checker unit tests and record there that this really doesn't need any permissions.

**Comment by scotwk** [comment]
@kapilt - I had to make modifications to the `ValueType` filter in order to make the tests work, so I took your approach and made `count` a type in `ValueType`.  Is this what you had in mind?

**Comment by scotwk** [comment]
@kapilt - I renamed it to `resource_count` (with an underscore, not a hyphen) because `cidr_size` used an underscore.  If you prefer with a hyphen let me know and I'll swap it.  (Or all hyphens can be translated to underscores if you want to support either form)

**Comment by kapilt** [comment]
Thanks. sounds good re underscore, at some point we'll have an underscore geddon with deprecation policy. we're pretty inconsistent as is between different actions and resources, in general i think we should favoring hyphen.

**Comment by scotwk** [comment]
I too favor the hyphen, as it means pressing one less key :)

**Pull request merged**
