### PR TITLE
set content-type to text/plain instead of text/Text

### PR DESCRIPTION
**Pull request by cmedley**
Sets email to text/plain (with text/Text it comes in as an attachment called noname in gmail)

### CODE REVIEW

**Comment by kapilt** [comment]
@JohnTheodore ... seems like this may have been broken for a bit then since the smtp support merge. original format was for ses api params, the values for that api don't correspond directly to proper mime types on the multipart mime, they need a separate mapping if transport is smtp or ses raw.

**Comment by cmedley** [comment]
@JohnTheodore  should i close this PR?  (or include multipart mime if smtp)

**Comment by JohnTheodore** [comment]
So if you want it working now, and this does it, might as well merge?

I have a larger PR that lets you explicitly declare the format from the yaml template. So you can set it to html or plain in the notify section when you link to the template, instead of relying on the file extensions. https://github.com/capitalone/cloud-custodian/pull/1201/files

I'm still soaking this PR, I'm writing some tests since there is no test coverage on the mailer. This is a good thing I can test for!

**Comment by cmedley** [comment]
That works for me!

**Comment by JohnTheodore** [comment]
btw, the only format people want are html and plain? we could add that as a json validation check

**Comment by cmedley** [comment]
Sounds right on format. May want to consider sending multipart/alternative content-type if both templates exist.   But was fine with it being either html or text.

**Pull request closed without merging**
