### PR TITLE
aws.ecr - lifecycle policy filter & set action

### PR DESCRIPTION
**Pull request by kapilt**
at the moment this is simple replacement of lifecycle policy, merges are a little tricky due to additional semantic rules that need to be adhered to. we'll also need a filter against lifecycle policy rules.

### CODE REVIEW

**Comment by McKaylTurner** [comment]
Is there a time frame on when this pull request will be merged with master?

**Comment by kapilt** [comment]
actually one other piece that i wasn't sure of.. this currently does a lifecycle policy replacement of extant lifecycle policies, not a merge. i'm a little unclear in practice how problematic that is.

**Comment by kapilt** [comment]
also this would need a lifecycle policy filter to have selective application to only repos missing an appropriate policy, the syntax on that isn't determined, proposals welcome.

**Comment by kapilt** [comment]
so as a stray man proposal on a filter syntax for ecr lifecycle, how about something like this

```
policies:
  - name: ecr-life
     resource: aws.ecr
     filters:
       - type: lifecycle-rule
          state: absent
          match:
             - selection.tagStatus: untagged
             - action.type: expire
             - key: selection.countNumber
                value: 30
                op: less-than               
```

which would filter in a repository if it didn't have a lifecycle rule which deleted untagged images in less than 30 days.
       
for just operating on repos without any lifecycles policies.

  ```
policies:
  - name: ecr-life
     resource: aws.ecr
     filters:
       - type: lifecycle-rule
          state: absent            
```

**Pull request merged**
