### PR TITLE
aws.firehose - set S3 destination encryption on delivery streams

### LINKED ISSUE #2746: Add support for Kinesis Firehose destination encryption
This one is a bit tricky, in that there are multiple possible types of destinations, each requiring a different KMS key.

### PR DESCRIPTION
**Pull request by troylar**
This PR resolves #2746 to support enabling encryption on S3 destinations for each of the four Firehose destination types: 

- Redshift
- ElasticSearch
- S3
- Splunk

The challenge here is that `update-delivery-stream` has a different payload for each destination type, so I've broken it out into four different unit tests to accommodate each. However, as this example demonstrates, we can run against all destination types in a single policy.

```
 policies:
 - resource: firehose
   name: test-firehose-encrypt
   filters:
     - or:
       - type: value
         key: "Destinations[0].S3DestinationDescription.EncryptionConfiguration.NoEncryptionConfig"
         value: present
       - type: value
         key: "Destinations[0].SplunkDestinationDescription.S3DestinationDescription.EncryptionConfiguration.NoEncryptionConfig"
         value: present
       - type: value
         key: "Destinations[0].ElasticsearchDestinationDescription.S3DestinationDescription.EncryptionConfiguration.NoEncryptionConfig"
         value: present
       - type: value
         key: "Destinations[0].RedshiftDestinationDescription.S3DestinationDescription.EncryptionConfiguration.NoEncryptionConfig"
         value: present
   actions:
     - type: encrypt-s3-destination
       key_arn: arn:aws:kms:us-east-1:12345:alias/aws/s3
```

### CODE REVIEW

**Comment by troylar** [comment]
Closing to make a fix

**Comment by kapilt** [comment]
not sure why drone's status check isn't reporting, looks successful https://ci.cloudcustodian.io/capitalone/cloud-custodian/6811

**Comment by troylar** [comment]
@kapilt I updated the latest from master, so we'll if that kickstarts it.

**Comment by troylar** [comment]
@kapilt Any concerns here?

**Comment by troylar** [comment]
@kapilt looks great . . . can you merge?

**Comment by kapilt** [comment]
looks like my changes weren't quite ready. i'm backed up for the next few weeks, but can try to address first week of october.

**Comment by troylar** [comment]
@kapilt Can we revisit this? We're getting ready to implement . . .

**Comment by kapilt** [comment]
hmm.. drone seems to be picking up a stale revision for some reason.

**Pull request merged**
