### PR TITLE
Make the cache aware of profiles (#1925)

### PR DESCRIPTION
**Pull request by scotwk**
#1925 

The cache was storing by region, resource, and query, but it ignored profiles.  I added that in to the cache key.

@kapilt - I tested on my end and it seems to work fine.  I can see the profile is stored in the cache file and when I test with profile that link to the same region in different accounts (skunkworks vs. my own personal account) the results are as expected.  It was a tiny change though - so are there any considerations I may have missed?

### CODE REVIEW

**Comment by kapilt** [comment]
its actually nicer to just use account id instead of profile.

**Comment by kapilt** [comment]
profile is an optional value, account id is a populated value, always present, and the proper scope of the cache, ie. you could have multiple profiles for the same account, there wouldn't be any value to storing the data separately for each vs the account level.

**Comment by scotwk** [comment]
@kapilt - good point.  Fixed.

**Comment by jhnlsn** [comment]
@scotwk thanks for the fix!

**Comment by scotwk** [comment]
@kapilt - looks like I introduced a test failure in the full test suite, and this got merged.  I don't have my computer handy that has my dev environment on it, but I'll try to get you a fixed tonight.

**Comment by scotwk** [comment]
@kapilt - test fixed.  Good to go.

**Comment by rbowlby** [comment]
Thanks a ton @scotwk !

**Pull request merged**
