### PR TITLE
Update iam.py to Allow for CloudTrail Event Filtering on iam-role

### PR DESCRIPTION
**Pull request by AndrewCi**
Fix for Issue #2510

### CODE REVIEW

**Comment by kapilt** [comment]
Thanks for the pull request, rather than re querying out the group id from the name, we can construct the id from the name statically. ie detect if string startswith arn and if not construct one using the group name. the question for doing that is if name includes the org path.

**Comment by kapilt** [comment]
i'll try and work on this, this morning, thanks again for the pr

**Comment by AndrewCi** [comment]
@kapilt no problem - was working on it more for the experience and to draw attention to the issue - figured there was a better way to do it. 

I will note though that the issue was that the AWS Config Item and the CWE only return GroupName/RoleName (not the ARNs) and that the get_resource function was only handling GroupID and RoleID. The solution needs a way to map GroupName/RoleName to the resource since that's the only available input. Unless you're suggesting just jumping from Name to ARN, but I believe the issue w/ that was it wasn't a consistent ARN format (depending on if it was AWS role or user created role etc.)

**Comment by AndrewCi** [comment]
[https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_identifiers.html#identifiers-unique-ids](url)

From AWS perspective GroupName/RoleName are unique on a per account basis, but there are specific use cases where the ID is useful (which aren't applicable from what I can see). I think using names from start to finish is probably the best way to do it. I wasn't exactly sure how to go about that though.

**Comment by AndrewCi** [comment]
Restarted this with an alternate implementation - let me know if the original implementation was more what you were looking for and I can push the old code (that I have stored locally)

**Comment by kapilt** [comment]
the only issue re the alternative implementation is that the enumeration api (list_roles, list_groups) doesn't support filtering using either Id or Name so we still need to override get_resources to do the minimal api work needed by retrieving the user via get_role/get_group. i've pushed a variation of the original impl that simplifies a little bit. nutshell if we're already retriving the group/role we can just return it from get_resources without invoking the base class method.

**Comment by AndrewCi** [comment]
Closing due to data (will reopen under different request)

**Pull request closed without merging**
