### PR TITLE
filter load balancers down to just ALBs

### PR DESCRIPTION
**Pull request by stenius**
Check to see if load balancers are ALB's before checking logging.
It was currently unfiltered and returning classic and application load balancers.

For PR #2706

### CODE REVIEW

**Comment by thisisshi** [comment]
Thanks for the PR, @stenius If you don't mind could you sign the CLA at the bottom of the README? Direct link here: https://docs.google.com/forms/d/e/1FAIpQLSfwtl1s6KmpLhCY6CjiY8nFZshDwf_wrmNYx1ahpsNFXXmHKw/viewform

**Comment by kapilt** [comment]
its better to do this in the policy, via a filter, ie this is filtering on load balancer attributes for type and logging, those are better in policy then hardcoded in code.

**Comment by tim-elliott** [comment]
@kapilt if the Custodian policy is for resource type app-elb then I would expect it the remainder of the filter to apply only to application load balancers.  That is what this code is fixing.  I was about to open an issue on this myself.

**Comment by tim-elliott** [comment]
The same problem exists in the `is-logging` filter, so the IsLoggingFilter() function needs the same fix.

**Comment by tim-elliott** [comment]
I hadn't picked up on the fact that app-elb was supposed to cover both application load balancers and network load balancers.  Since the logging filters really only apply to application load balancers, it seems like we either need a separate resource for net-alb or the filters that don't apply to both should make checks to ensure that the correct type of resource is being checked.  I'm open to either solution.

**Pull request merged**
