### PR TITLE
Support for Child Resources

### PR DESCRIPTION
**Pull request by Sutto**
This is my first attempt at something to solve #980, by approaching #584 

It still requires some tweaks - and I'm not 100% sure this is the right level to do it / right approach but would love some initial feedback.

This lets you declare a `parent_enum_spec` on the resource type model, which declares how to extract ids from the parent.

Things this doesn't yet do, but I'd like to consider:

* Include the parent since we're already loading it.
* Should this happen higher? In the query manager possibly?
* How does this effect existing rrset policies?

I modified the existing rrset resource to support it (i'm not sure how anyone used it before directly, if you have an example policy that'd be amazing - so I can test compatability) - Since it appears ec2 is the only that allows injecting options / params to the api key from a policy?

Likewise, I've added an EFS mount target resource to test  - which is probably a good candidate for where injecting the parent resource may make sense (possibly under a specified key?)

### CODE REVIEW

**Comment by Sutto** [comment]
If we were to push it into the `QueryResourceManager` level, we'd possibly be able to simplify the spec to `('hostedzone', 'Id', 'HostedZoneId', False)` - and let it do resolution of the hostedzone model as soon as possible.

Oh, and the reason you need to specify the id field, is to deal with (in theory), endpoints in which the input field is not the id field for that resource.

**Comment by kapilt** [comment]
Very cool! Going to need a day or two to digest nothing but meetings and travel atm. I was hoping to reuse the parent resource manager class directly (ala parent_manager = self.get_resource_manager(parent_type)) , and have a ChildResourceManager subclass of query resource manager that could encapsulate the parent lookups.

**Comment by Sutto** [comment]
All good!

Yehp, I'm happy to rewrite the patch in whatever style works for you.

For context, the reason I pushed it here to the `ResourceQuery` was around the iteration aspect - For instance, in the rrset API, you have to call the API endpoint once per HostedZoneId - I figured that was most likely a part of the `Describe-` based source or lower.

That said, pushing it up in a ResourceQueryManager / a subclass of that does make a lot of sense - I'll have a play in the mean time and see what it looks like :)

**Comment by kapilt** [comment]
re iteration aspect, generically its unavoidable to call the list child per parent, it can be mitigated by providing for a policy query filter here that effectively limits the parents to the set of interest but that can be a future enhancement.

most of the structure here looks a bit cleaner with a separate child resource subclass for keeping the logic localized to child resources. looking forward to seeing play results. happy to dive in for collab on a branch if thats helpful. cheers.

**Comment by kapilt** [comment]
started working on getting this merged, one question, i'm not finding any child resources where the parent would be batchable? are you aware of any?

**Comment by kapilt** [comment]
i've pushed my changes to the branch here, https://github.com/kapilt/cloud-custodian/tree/child-resources,  it looks like i can push to your branch as well if your game and then merge it from this pr, else i'll open up a new one.

**Comment by Sutto** [comment]
awesome - I'd say leave on your branch - it keeps it seperate (plus I need to update our internal build) - thank you for picking up and having a look at this. Things have been crazy so I didn't get to pick it up again for a bit, nice to see you've made progress on it.

Re. batchable, I thought there were some, but I can't think of them or find them off the top of my head.

**Comment by kapilt** [comment]
merged in #1533, thanks again

**Pull request closed without merging**
