### PR TITLE
Cli hygiene

### PR DESCRIPTION
**Pull request by kapilt**

### CODE REVIEW

**Comment by kapilt** [comment]
it would be nice to explore moving to click or alternative cli parser, argparse does get a bit painful for formatting, anyways this branch extends our usage of argparse, to enable better grouping of common options and better help output, also some micro optimization around cli execution time via import delays.

LGTM

**Comment by mrpudn** [comment]
What are your thoughts on [`docopt`](https://github.com/docopt/docopt)?

I've been using it for CLI projects for a while now and have found it to be pretty intuitive.

**Comment by kapilt** [comment]
so my contendors at the moment are click and docopt, with a few others to checkout more (Argh on argparse) Their quite a bit different mentalities, programmatic vs. purely declarative. argparse's issues are that it couples a suboptimal ux into its defaults, docopt resolves that by doing a parser on declarative freetext. The delta becomes the difficulty of parsing customization vs. a better programatic data models and templating ui. Given custodian's goals, we need to expose many resources in many ways, the later is more of interest. That said the cross language ux of docopt is also nice and worth noting.

**Comment by kapilt** [comment]
i guess the bigger question with docopt is the lack of validation, they seem to point to deferring to secondary libraries, and while we use jsonschema throughout custodian, the error messages are obtuse compared to the inline field/param validation of most of the cli parser libs.

**Comment by mrpudn** [comment]
Hmm, I suppose it does take a more minimalist approach.

I've always done my own validations, but they were fairly trivial. Validation with [`schema`](https://github.com/keleshev/schema) doesn't look too terrible.

click looks like a pretty solid option, though. It even features [`bash completion`](http://click.pocoo.org/5/bashcomplete/).

**Pull request merged**
