### PR TITLE
Vendor in ipaddress

### LINKED ISSUE #1784: Lambda w/ py2.7 remote and py3 local hits SyntaxError
Hi All,

I just started using custodian and was looking at 
http://www.capitalone.io/cloud-custodian/docs/policy/lambda.html#cloudwatch-events

1) I created IAM role using this link 
https://aws.amazon.com/premiumsupport/knowledge-center/start-stop-lambda-cloudwatch/

2) I created my rule as below and saved it as policy.yml

```
policies:
  - name: my-first-policy
    mode:
        type: config-rule
        role: arn:aws:iam::123456789012:role/lambda_start_stop_ec2
    resource: ec2
    filters:
      - "tag:custodiantest": present
    actions:
      - stop
```

3) Ran command from my machine
custodian run -s . policy.yml --region ap-southeast-2
I created an EC2 machine with tag "custodiantest". 

Saw Logs in machine as below

ubuntu@ip-1xx-xx-x-xxx:~/custodiantest$ custodian run -s . policy.yml --region ap-southeast-2
2017-11-14 04:54:31,691: custodian.policy:INFO Provisioning policy lambda my-first-policy
2017-11-14 04:54:31,756: custodian.lambda:INFO Publishing custodian policy lambda function custodian-my-first-policy

Cloud watch error logs shown in below image.
custodian_error

Can you please let me know what is going wrong.
Is this an existing bug?

Thanks in advance

Vishnu

### PR DESCRIPTION
**Pull request by whit537**
Fixes #1784

### CODE REVIEW

**Comment by whit537** [comment]
Ready for review, @kapilt.

**Comment by whit537** [comment]
note to self: check on pypy

**Comment by kapilt** [comment]
the pypy stuff was in regards to the namespace package test fwiw

**Comment by whit537** [comment]
Rebased, was 362d9e70f7d3b010268d29f96408cc1de051d39c. Debugging ...

**Comment by whit537** [comment]
Appears to be passing locally. Steps to repro?

```
(pypy) $ pytest tests/
[...]
================================== 823 passed, 1 skipped in 207.95 seconds ===================================
```

**Pull request merged**
