### PR TITLE
Add windows compatability - use platform.uname, manually delete named tempfiles.

### PR DESCRIPTION
**Pull request by jozzas**
These changes make mu.py windows compatible and shouldn't break functionality on Linux.

Addresses #113

### CODE REVIEW

**Comment by kapilt** [comment]
Thanks!, looks good, but it looks like it needs a rebase/merge with master.

**Comment by jozzas** [comment]
Branch updated!

**Comment by kapilt** [comment]
sorry one last thing, we have a contributor licenses agreement as referenced by the bottom of our readme that we need signed before i can merge. Thanks

https://docs.google.com/forms/d/19LpBBjykHPox18vrZvBbZUcK6gQTj7qv1O5hCduAZFU/viewform

**Comment by jozzas** [comment]
@kapilt No problem, I've signed the agreement now. Thanks!

**Comment by kapilt** [comment]
merged, thanks!

**Pull request merged**
