### PR TITLE
Fixing testing output that came from refactoring StringIO to python3 …

### PR DESCRIPTION
**Pull request by alfredgamulo**
…compatible modules

### CODE REVIEW

**Comment by whit537** [comment]
@alfredgamulo Could I get a little more context on what testing output broke? What was the output previously, and what is it post-#1234?

**Comment by alfredgamulo** [comment]
@whit537 Check out these two drone outputs:

https://ci.cloudcustodian.io/capitalone/cloud-custodian/2826

https://ci.cloudcustodian.io/capitalone/cloud-custodian/2859

This update cleans up the output for `test_route53_hostedzone_tag_exception` and `test_encrypt_volumes`

**Comment by alfredgamulo** [comment]
I don't understand why travis is failing due to missing modules, but the trunk from which I merged master passes. @kapilt?

**Comment by kapilt** [comment]
@whit537 ping

**Comment by whit537** [comment]
Confirmed locally that `py36` passes on `master` and fails on this branch. Debugging ...

**Comment by whit537** [comment]
> travis is failing due to missing modules

Is it? Afaict, it's failing [because](https://travis-ci.org/capitalone/cloud-custodian/jobs/246214379#L2131) "Some tests required to pass under Python 3.6 didn't." The reason the three tests in question don't pass  with a0a641ba02216242512d028dfb5068769676581e is because, now that `capture_logging` returns something that is fundamentally a `BytesIO`,  `getvalue()` returns a bytestring instead of a text string, subtly but crucially affecting the subsequent behavior in the relevant tests.

Does that get you pointed in the right direction, @alfredgamulo?

**Comment by alfredgamulo** [comment]
@whit537 gotcha, I thought that AmbiguousIO would handle that issue as I saw you use in another class. I'll close this PR and try to figure out another way to clean up this test output.

**Comment by whit537** [comment]
Well, I think it was a good start to factor out AmbiguousIO for usage in `capture_logging`, but then you either need to make sure the tests work with bytes, or you need to override `getvalue` to decode to a text string.

**Pull request closed without merging**
