### PR TITLE
Fixed Redshift snapshot tagging (issue #1759)

### PR DESCRIPTION
**Pull request by seth-carroll**
The generated ARN for the Redshift snapshot was missing the cluster ID, which caused the tag operation to fail. It looks like this was fixed in one place in the redshift.py file but not in the other two occurrences. 

I also fixed a 'ClusterIdentifer' typo.

Confirmed the functionality with this policy:
```
policies:
  - name: redshift-required-tags
    resource: redshift-snapshot
    filters:
      - type: value
        key: "SnapshotIdentifier"
        op: equal
        value: "manual-snap2"
    actions:
      - type: tag
        key: Owner
        value: Seth
```

Results:
```
custodian run -s output tag-redshift-snap.yml --verbose
2017-11-08 10:37:33,655: custodian.cli:DEBUG using default region:us-east-1 from boto
2017-11-08 10:37:34,211: custodian.commands:DEBUG Loaded file tag-redshift-snap.yml. Contains 1 policies
2017-11-08 10:37:34,294: custodian.output:DEBUG Storing output with <DirectoryOutput to dir:output/redshift-required-tags>
2017-11-08 10:37:34,297: custodian.policy:DEBUG Running policy redshift-required-tags resource: redshift-snapshot region:us-east-1 c7n:0.8.27.0
2017-11-08 10:37:34,299: custodian.cache:DEBUG Using cache file /root/.cache/cloud-custodian.cache
2017-11-08 10:37:34,299: custodian.resources.redshiftsnapshot:DEBUG Using cached c7n.resources.redshift.RedshiftSnapshot: 60
2017-11-08 10:37:34,300: custodian.resources.redshiftsnapshot:DEBUG Filtered from 60 to 1 redshiftsnapshot
2017-11-08 10:37:34,300: custodian.policy:INFO policy: redshift-required-tags resource:redshift-snapshot region:us-east-1 count:1 time:0.00
2017-11-08 10:37:34,300: custodian.output:DEBUG metric:ResourceCount Count:1 policy:redshift-required-tags restype:redshift-snapshot scope:policy
2017-11-08 10:37:34,376: custodian.actions:DEBUG Tagging arn:aws:redshift:us-east-1:123456789012:snapshot:my-test/manual-snap2 with [{u'Value': 'Seth', u'Key': 'Owner'}]
2017-11-08 10:37:35,010: custodian.policy:INFO policy: redshift-required-tags action: redshiftsnapshottag resources: 1 execution_time: 0.70
```

### CODE REVIEW

**Comment by seth-carroll** [comment]
This fixes issue https://github.com/capitalone/cloud-custodian/issues/1759

**Comment by alfredgamulo** [comment]
lgtm

**Comment by alfredgamulo** [comment]
lgtm

**Comment by jhnlsn** [comment]
Thanks @seth-carroll! It looks like we are missing test coverage around redshift tag actions and probably why some of this slipped through.

**Comment by jhnlsn** [comment]
Example snapshot arn:

```
arn:aws:redshift:region:account-id:snapshot:cluster-name/snapshot-name
```

**Comment by jhnlsn** [comment]
lgtm

**Pull request merged**
