### PR TITLE
Update ec2offhours.rst

### PR DESCRIPTION
**Pull request by FireballDWF**
Make offhour consistent with comment and name

### CODE REVIEW

**Comment by kapilt** [comment]
Thanks @FireballDWF lgtm, would you mind signing our contributor license agreement ref'd in the readme, link https://docs.google.com/forms/d/19LpBBjykHPox18vrZvBbZUcK6gQTj7qv1O5hCduAZFU/viewform

**Comment by FireballDWF** [comment]
Done

**Comment by kapilt** [comment]
Thanks, and merged. 

also fwiw, unrelated but i remember we had quick talk about detecting alarms on resources last year, there's a  branch with a custodian equivalent https://github.com/kapilt/cloud-custodian/tree/alarm-filter stalled on time for writing unit tests though.

**Comment by FireballDWF** [comment]
Ok, will review that once get past a few deliverables with my current
client.

**Pull request merged**
