### PR TITLE
New actions for ASG: terminate, restore

### PR DESCRIPTION
**Pull request by andyspiers**
Hi,

We are using OffHours to shut down autoscaled instances out of hours. We use the existing suspend/resume actions in some cases but they didn't work well for us in others, for a few reasons:

- for many dev clusters we turn off at "offhour" but we don't define an "onhour", so we do not turn them on with Custodian. Instead we want them to be restored by Terraform when the next pipeline run is triggered. This doesn't work well with suspend/resume because Terraform strips the suspended processes on the ASG but then stopped instances just get terminated and new ones have to be recreated anyway.

- sometimes we *prefer to recreate* the instances at "onhour" not just restart them, so that we get pristine instances every day, and so we're not paying for EBS volumes of stopped instances

So I have implemented 2 new actions for ASGs which are complementary to suspend & resume:

- *terminate*: terminates all the instances in an ASG by setting MinSize and DesiredCapacity to zero. Optionally records the previous size values in a configurable tag, in a semi-colon delimited format like `DesiredCapacity=2;MinSize=2;MaxSize=2`

- *restore*: reads ASG size parameters from a tag (required) and restores them to the ASG. In the policy that I'm running at work, we add an additional action to remove the tag but this isn't mandatory so therefore is not baked into this new action.

It's my first pull request so all review/comments is very welcome. I have not signed the contributor agreement yet but I can hopefully do this tomorrow after checking with work.

Thanks!
Andy

### CODE REVIEW

**Comment by andyspiers** [comment]
BTW I did try to implement this with asg.actions.resize (after fixing it to allow setting arbitrary size modifications) rather than creating a new action but:
- there was no sensible way to access resource attributes (previous values for MinSize and DesiredCapacity) and assign them to a new tag
- I didn't fully understand what functionality asg.actions.resize was trying to implement and there were no unit tests for me to ensure I didn't break it

**Comment by kapilt** [comment]
Thanks for the PR, tests, and the details on the use cases! These actions feel a bit like different parameters on a resize action.  The concern is on the action naming (ie. terminate vs delete) causing user confusion, and a current project direction towards better orthogonality on exposed filters/actions.  Our existing resize action is pretty minimal (use case for it was resize desired to extant), but i'm wondering if we could extend it for these use cases.  ie. 

terminate via
```
actions:
  - type: resize
     min-size: 0
     max-size: 0
     desired-capacity: 0
     save-options-tag: OffhoursPrevious
```

restore via
```
actions:
  - type: resize
     restore-options-tag: OffhoursPrevious
```

Thoughts? let me know on the CLA signing, happy to help with getting this merged.

**Comment by andyspiers** [comment]
Thanks for the input and suggestions!

This is what I originally tried (on my branch https://github.com/andyspiers/cloud-custodian/commits/asg-min-size ) but then though *new* actions would be cleaner, but I'm happy to switch back to refactoring the resize action to achieve this if you think this reduces confusion.

We'll need to add a test for resize though, which is where I got stuck last time .... can you clarify exactly what it's suppose to do? I couldn't really understand why you'd need to set desired to actual, because unless something broke, actual *would* always be equal to desired, right?

Andy

**Comment by kapilt** [comment]
yeah.. we had a case of asgs with invalid launch configs that were spinning, i whipped that up as a stop gap for the launch/run instances churn.

**Comment by andyspiers** [comment]
Hey Kapilt,

One of the things I struggled with on asg.actions.resize was the schema definition.

For example:
```
schema = type_schema(
        'resize',
        min_size={'type': 'int'},
        max_size={'type': 'int'},
        desired_size={'type': 'string'},
        save_options_tag={'type': 'string'},
        restore_options_tag={'type': 'string'},
        required=())
```

min/max should logically be "int"

desired_size however could either be the string "current" (to set min/desired to current number of instances) *or* an integer value for desired size.

When min/max/desired are all numeric values, the above schema requires ugly and confusing policy YAML because desired _needs_ quotes but min/max must _not_ have quotes. Is there a way to define a schema which accepts an integer *or* a string?

If not I would suggest that we should consider deprecating desired_size and replacing with maybe a boolean property like "desired_to_extant" or "desired_to_current".

What do you think?

**Comment by kapilt** [comment]
its possible to in the schema support both forms via a oneOf syntax in jsonschema, couple of examples extant like awslambda.py remove-statements taking matched string or statement ids. deprecation takes a while, its not something we've done  at historically, we need a better framework for that and a stated/documented policy for deprecation (hoping to tackle for 0.9.0), but at the moment we try to give very strong compatibility considerations for policy authors.

**Comment by andyspiers** [comment]
I've tidied up the refactor of asg.actions.resize as per your recommendations and, given that it's a different bunch of commits from a different branch, filed it as a new pull request: https://github.com/capitalone/cloud-custodian/pull/1757

**Pull request closed without merging**
