### PR TITLE
Service limits action - formatting the request

### PR DESCRIPTION
**Pull request by gitchristo**
Modifications:
1. Create a single case for each main service type while including all the sub service types in the same case
2. Include the current limit, current usage and new requested limit in the created request.
3. Replace the limit increase percentage with a quantifiable amount to be increased, depending on the current limit
4. Included the account ID # in the subject (currently when AWS responds, the emails will not carry the account name, making it difficult to locate the account in order to log in and close the relevant case once resolved).

e.g. Case 
subject---  [Account:134135245324]Raise the following limit(s) of EBS in us-east-1
Please raise the below account limit(s); 
 
Increase Active volumes by 1000 in us-east-1 
         Current Limit: 5000
         Current Usage: 250
         Set New Limit to: 6000
        
Increase Provisioned IOPS by 20000 in us-east-1 
         Current Limit: 100000
         Current Usage: 21000
         Set New Limit to: 120000

### CODE REVIEW

**Comment by kapilt** [comment]
re ci failure you have a doc string issue thats causing a problem

```
Warning, treated as error:
/home/travis/build/capitalone/cloud-custodian/c7n/resources/account.py:docstring of c7n.resources.account.RequestLimitIncrease:22:Block quote ends without a blank line; unexpected unindent.
make[1]: *** [html] Error 1
make[1]: Leaving directory `/home/travis/build/capitalone/cloud-custodian'
make: *** [sphinx] Error 2
ERROR: InvocationError: '/usr/bin/make sphinx'```

**Comment by kapilt** [comment]
for 2. i think we need a new option for this, we want to maintain backward compatibility, and reusing the `percent-increase` option as a not a percent is non-intuitive. adding a `amount-increase` as a delta value or `resource-count` as an absolute would be better.

**Comment by gitchristo** [comment]
WIP

**Comment by gitchristo** [comment]
Added new option to be enable to specify an exact value to be raised (either one of percent-increase or amount-increase can be used in the policy)

**Comment by kapilt** [comment]
i almost feel like we want an additional option here, if your creating an account you want to be able to increase to a set number/value.. ie set this value to 2000, but this is probably workable even in that context.

**Pull request merged**
