### PR TITLE
Vpc augment

### PR DESCRIPTION
**Pull request by alfredgamulo**
pre-requisite merge: https://github.com/capitalone/cloud-custodian/pull/1315

This pull-request adds universal-augment from the aforementioned PR to VPC resources.

### CODE REVIEW

**Comment by kapilt** [comment]
hmm.. we should talk about this offline, its currently at 30k diff.

**Comment by kapilt** [comment]
there's a a lot of extraneous content in here due to not cleaning up the network resources in the account before recording.

**Comment by kapilt** [comment]
I'd suggest trying to drop everything not related to the resource tags augment (aka tagging.GetResources_*.json)  from the changes on the recorded data

**Comment by kapilt** [comment]
so there seems to have been a disconnect or lack of testing wrt to the need for augment on most of these resources, as they already have tags in their describe outputs, so much of this should be reverted..

**Comment by kapilt** [comment]
@alfredgamulo @ocampocj ^

**Comment by alfredgamulo** [comment]
@kapilt really sorry about that. fwiw, the revert pr: https://github.com/capitalone/cloud-custodian/pull/1499

**Comment by ocampocj** [comment]
Thanks for catching @kapilt and taking care of the revert @alfredgamulo.  Let's talk more on Monday about this.

**Pull request merged**
