### PR TITLE
Delete transient tags on newly encrypted volume

### PR DESCRIPTION
**Pull request by tjordan-vrts**
Existing process was not cleaning up transient tags. Added code to delete transient maid tags left behind on newly encrypted volume.

### CODE REVIEW

**Comment by kapilt** [comment]
lgtm, but it feels like we need to get a recording of just the delete tags to insert into the extant placebo dir to cover this. also curious why the extant test wouldn't error without a recording of the delete tags.

**Comment by jesselang** [comment]
We're in process of refactoring the test case. We'll let you know when we're ready for final review.

**Comment by kapilt** [comment]
the easiest thing might just be dropping in a delete tags recorded response into the test directory, there's a good amount of setup involved, that needs sanitizing. ping me on gitter if you'd like to discuss additional options.

**Comment by jesselang** [comment]
@kapilt, do you have a tool for sanitizing the placebo data we're recording?

**Comment by jesselang** [comment]
Hey @kapilt, I think we're ready for another review here. The test case has been improved to verify that the resulting volume is encrypted, delete on termination matches the source, and the tags created during the process are removed.

**Comment by jesselang** [comment]
Anything more to be done here?

**Pull request merged**
