### PR TITLE
Additional tests

### PR DESCRIPTION
**Pull request by skurfer**
A grab bag of things I was able to add tests for a while back. I was going to wait until there was more, but if you want to keep the requests small, we can start here.

I’m not sure if the policies used in the tests are appropriate in every case, but they do pass.

### CODE REVIEW

**Comment by skurfer** [comment]
After `master` was merged, I can reproduce the failing test locally. I’ll get it fixed.

**Comment by kapilt** [comment]
lgtm, thanks!

**Comment by kapilt** [comment]
this branch seems to be causing intermittent failures on master

**Comment by skurfer** [comment]
There seem to be quite a few ways to write tests that pass locally, but fail the automated checks.

Is there anything we can do to make the CI environment more closely resemble the development environment? For example, `make test` sets a few environment variables for AWS, but that doesn’t seem to happen when Drone runs tests.

Conversely, are there things we can do to make our local environments more like the CI server?

**Comment by kapilt** [comment]
this case in particular that caused this to fail was depending on string representation in json which is a bad idea and implementation dependent. 

the failure happened on pypy drone test run.

cleaning out aws env vars should do it as far as env deltas beyond sw packages.

the config for travis and drone is in the repo.

**Pull request merged**
