### PR TITLE
Add 'rds-snapshot' resource.

### LINKED ISSUE #173: Ability to manage RDS DB snapshots
I'd love to be able to manage RDS DB snapshots as we do EBS snapshots:
* A new resource type (e.g. `rds-snapshot`)
* An associated `age` filter
* An associated `delete` action

### PR DESCRIPTION
**Pull request by ewbankkit**
* Add resource and associated `age` filter and `delete` action
* Add documentation
* Add `ebs-snapshot` documentation
* Add test and Placebo data
* Fixes #173

### CODE REVIEW

**Comment by ewbankkit** [comment]
There was no [skew](https://github.com/scopely-devops/skew) resource type for RDS DB Snapshots so I used the old-school `ResourceManager` base class.

**Comment by kapilt** [comment]
ugh.. just merged something which invalidated this, re skew base, its really easy to roll your own, see the bottom of vpc.py for a custom one.

**Comment by ewbankkit** [comment]
will do.

**Comment by ewbankkit** [comment]
OK, modified as requested

**Comment by kapilt** [comment]
lgtm

**Pull request merged**
