### PR TITLE
code-block docstring fix

### PR DESCRIPTION
**Pull request by jhnlsn**
Related to issue #1888.

code-block needs to have 2 colons after it and has to be on the same dent as the `"""`

This should add a lot of example policies to our api documentation

### CODE REVIEW

**Comment by kapilt** [comment]
curiosity have you verified the rendered output is fixed?

**Comment by kapilt** [comment]
hmmm, just took a look at the current docs, looks schema rendering also went awol.

**Comment by jhnlsn** [comment]
I did verify the changes locally after learning how to render the html.  it does not appear that `make docs` works out of the box, you need to have run `tox -e docs`.  So i'm not sure which command is preferred, but `tox -e docs` seems to do the trick just fine.

**Comment by jhnlsn** [comment]
@kapilt what schema docs are you referring to?

**Comment by kapilt** [comment]
thanks, the schema reference was unrelated to this pr, its wrt to the inline jsonschema rendering of the class attribute schema.

**Pull request merged**
