### PR TITLE
Add has-inline-policy filter for iam-user resource

### PR DESCRIPTION
**Pull request by scotwk**
Code is ready.  Just waiting on confirmation from @bobrich and then I will add a test and remove WIP label.

Issue #1621

### CODE REVIEW

**Comment by bobrich** [comment]
Precisely!  Thank you!

**Comment by scotwk** [comment]
@bobrich - I just need to write a test and then it'll be ready to merge.  Thanks.

**Comment by scotwk** [comment]
@kapilt - ready for review

**Comment by kapilt** [comment]
the testing in here is a bit questionable its recording 1800 lines of json for a 20 line code diff, ideally it would add a filter to drop the excess recording data. There's also overlap here with the user-policy filter except this filter queries the data only to drop the results on the floor as an existence check, I'd rather handling of the use case via implementing the value_type == 'resource_count' on the extant user policy and a doc example.

**Comment by bobrich** [comment]
I wasn't aware of the approach as suggested by @kapilt but can understand why it makes sense.  I gave it a go and found that it works great with managed policies, but current iam-user policy filter doesn't collect inline policies, so it doesn't achieve the objective.  

I tried appending the inline ones to c7n:Policies via list_user_policies()/get_user_policy(), but the result is weird because the schema is different.  Attached policies just have a blob of metadata and bury the policy document behind the version system.  The inline policies actually return the policy document and essentially nothing else.

Hrmm.

**Comment by scotwk** [comment]
@bobrich @kapilt - What's the status of the approach here?  I didn't fully understand the discussion, but I did reduce the amount of test data recorded per Kapil's request.

**Comment by kapilt** [comment]
per the discussion (querying data on a set to do a boolean set test) not sure this is where we want to go, given we have extant filter capabilities that encompass this set comparison already.

**Comment by bobrich** [comment]
@scotwk Thanks for giving this a go.  Not sure how to 'fix' this as inline policies are just as valid from an IAM perspective of course, but are wonky to deal with as they are essentially user attributes rather than a versioned managed policy linked by a reference.

**Comment by kapilt** [comment]
resurrecting this for more discussion, did some more research, and while it would be nice to combine this into extant user policy filter, the standalone usage is going to be simpler.

**Comment by scotwk** [comment]
@kapilt - lmk if you need changes on my end

**Comment by bobrich** [comment]
Thanks folks!

**Pull request merged**
