### PR TITLE
Reduce log spam at Travis

### PR DESCRIPTION
**Pull request by whit537**
Aimed at https://github.com/capitalone/cloud-custodian/issues/1082.

### CODE REVIEW

**Comment by whit537** [comment]
Lessee what drone/travis do with 1013526e7361d3c7c05d03b17fdb19ecbababeb1 ...

**Comment by whit537** [comment]
Turn down custodian debugging as well, @kapilt?

**Comment by kapilt** [comment]
this isn't an issue in drone, just the travis output with py.test

**Comment by kapilt** [comment]
i'll play around with it, i think for now just turning of the `-v` on py.test solves most of the verbosity.

**Comment by whit537** [comment]
Here's my local notes fwiw.

```
I think the problem is placebo output. It's too verbose.

We are getting DEBUG messages when we don't really need them.

If I run a single file or even two specific files, I get no placebo DEFAULT output.

If I run `py.test tests/`, I *do* get DEFAULT output. Hmm ...

Fascinating! Logging the debug flag to Pill shows no difference between the two
cases: both are False.

        for f in inspect.stack():                                                    
            filename = os.path.basename(f[1])                                        
            if filename.startswith('test_'):                                         
                break                                                                
        else:                                                                        
            filename = '???'                                                         
        open('log', 'a+').write('{}  {}\n'.format(filename, debug))


looking in pill.Pill.attach, it's about handler installation:

   (Pdb) LOG.debug('foo')
    No handlers could be found for logger "placebo.pill"

```

**Comment by whit537** [comment]
The point being that I never used `-v` locally and I still got voluminous DEBUG output from placebo. I think `-v` is a red herring but happy to be proven wrong. :)

**Comment by kapilt** [comment]
it looks like its the -s flag which is doing a different capture mode then what we're do with nose. with nose we let through stdout, where was in py.test that -s defaults to letting through stderr/stdout. simply omitting the -s flag resolves the issue.

**Comment by whit537** [comment]
Hmm ... thought I tried that but I can revisit. I don't use `-s` locally and I still get placebo debug logs.

**Comment by whit537** [comment]
Alright, let's see what Travis does with c55a4d3c255568ff224350e8722e1944280dfda5 ...

**Comment by whit537** [comment]
Well I'll be. Sorry for the runaround!

Good now, @kapilt?

**Comment by kapilt** [comment]
lgtm, thanks. although i wonder if we do set the log levels if we can get some marginal test speeds up.

**Pull request merged**
