### PR TITLE
Add --ascii option for printing reports

### PR DESCRIPTION
**Pull request by scotwk**
Will print reports in formatted ASCII instead of CSV.  (CSV remains the default).

This uses a library I found called `dashtable` (https://github.com/doakey3/DashTable).  I'm not sure if you have a policy about what external libraries you depend on.  It wouldn't be too hard to replicate the functionality if needed.

Issue #683 

WIP - fully functional but no tests yet.  Wanted to get review before investing more time.

### CODE REVIEW

**Comment by kapilt** [comment]
re deps, sanity check on upstream maintenance and license. tabulate looks more capable and active.

**Comment by scotwk** [comment]
@kapilt - ok, swapped to tabulate and added a test.  Good to go.

**Comment by kapilt** [comment]
let's try --format table/ascii/csv  default to csv

**Comment by scotwk** [comment]
@kapilt - Per your suggestion on the call I swapped `--ascii` to `--format` and made the default be csv.  I decided to not error check user input for the format because if they specify anything that is invalid then tabulate defaults to the simple format.

I added a blurb in the reports help about possible formats:

```
$ custodian report --help
...
  --format FORMAT       Format to output data in (default: csv). Options
                        include simple, grid, rst
...
```

I specifically called out those three.  Others are available.  Some, (plain, pipe, orgtbl), look rather similar to ones I mentioned and I didn't think it was necessary to list too many options.  And others (mediawiki, latex) are not likely to be useful.  But I didn't restrict them in the code.

**Comment by scotwk** [comment]
@kapilt - just saw your comment from before my commit.  I can change to those keywords.  How would you map it?

table -> tabulate 'grid' format
ascii -> tabulate 'simple' format

**Comment by kapilt** [comment]
what you got looks good as is, thanks!

**Comment by scotwk** [comment]
per phone call - use argparse choices and only pass through select options

**Pull request merged**
