### PR TITLE
cStringIO → io, and fix test failures thus exposed

### PR DESCRIPTION
**Pull request by whit537**
This includes an extension to `ratchet.py` to fail on unexpected successes, with a prompt to add to `ratchet.py`.

Part of #705. Includes #1214 and #1234, so I will rebase once those are in, or you can merge all at once here.

### CODE REVIEW

**Comment by whit537** [comment]
Travis is here and green, though absent on #1214 and #1234. Since it's here I think I won't spend too much time debugging missing Travis over on those.

**Comment by kapilt** [comment]
there still seems to be an issue passing the travis coverage to coveralls here.

**Comment by whit537** [comment]
Rebased, was 53ae68cc6e2bc975a3cd456d3c34aa370cc75514.

**Comment by whit537** [comment]
Closing in favor of #1285.

**Pull request closed without merging**
