### PR TITLE
Minor sphinx fixes

### PR DESCRIPTION
**Pull request by scotwk**
A few small fixes to docstrings and Sphinx rst files.  This removes some warnings in the `make sphinx` output and fixes a few problems in the generated HTML.

### CODE REVIEW

**Comment by kapilt** [comment]
Thanks! we've got a doc writer/editor that's due for an incoming pull request today for some structural changes on the docs (still sphinx just different layout), i'm going to defer on this till that's merged.

**Comment by kapilt** [comment]
looks like a conflict on offhours.py

**Comment by kapilt** [comment]
lgtm

**Comment by scotwk** [comment]
@kapilt - fixed the merge conflict.  Should be good to go now.

**Comment by kapilt** [comment]
the diff is a bit odd since it has other commits mingled in, but the overall looks fine, thanks.

**Pull request merged**
