### PR TITLE
Allow setting execution options in lambda

### PR DESCRIPTION
**Pull request by benjvi**
This makes the same execution options available in lambda as in a custodian run so that users may choose to override the default lambda execution settings.

Primarily, the motivation was to enable role assumption into other accounts for policy enforcment but this may also be useful for other use cases (eg --dry-run??)

### CODE REVIEW

**Comment by kapilt** [comment]
thanks, this looks interesting, i'm curious to understand the use case a bit more, afaics that would only work for periodic lambdas, else the event source is mismatched to the lambda target (region, account)

**Comment by benjvi** [comment]
Yes, you're right, I hadn't thought about the event-driven case. I am using it only in the periodic mode. When we have event-driven lambdas they are deployed directly into the account to which the policy applies

We're looking at a centralised model, so there is a 'security' account which can find non-compliant resources in all 'workload' accounts. At the moment we only send alerts from here into a centralised topic (I need to make another PR for this). This gives assurance that any malicious activity in an account will be detectable - even if only due to policy execution failure.

I've also looked a bit before at cross-account access directly through resource policies, but if I remember correctly that would only work for specific resource types.

**Comment by kapilt** [comment]
yeah we typically handle that use case of multi-account periodics outside of lambda, via an instance that can role assume into n accounts and run a consistent set of policies across them and via just doing --assume on the cli. 

doing periodic full account sweeps in lambda constraints has a few more of a challenges depending on the size of an account wrt to number of resources (due to time constraint), and the number of policies and frequency of period (due to in ability to use a local state cache across policies results in extra api calls), plus the issues with the event modes underlying source not supporting it (and still needing target account footprint on event sources). ie. i'd recommend lambda for events based policies either on trail events or using custodian's support for config rules for whole account evaluation but effectively on per resource events. if your goal is zero footprint in the workload account, you'll have better efficiency on instance as you increase the number of policies being evaluated.

all that said, i think this request (lambdas targeting other accounts and regions) has come up a few times before, and it makes sense to support. The remainder is figuring out some execution mode validation to prevent invalid combinations resulting in runtime time failures (config supports cross account within same region, periodic supports all options, and i'll have to check on cloudwatch events re cross account). 

wrt to this pr i think the delta would be adding docs, also doing a merge of the extant config rather than a replace with execution-options.

**Comment by benjvi** [comment]
OK, sounds good to me! Hopefully I'm going to be able to pick this up again tomorrow and make the updates. 

Can you clarify on what you meant by merge, didn't get that? The current behaviour should be to only override the default settings set in the handler where a value is explicitly set in execution-options

**Comment by kapilt** [comment]
your right re merge, lambda handler Config class puts in sane defaults for the empty method, looks good.

**Comment by benjvi** [comment]
@kapilt added docs (finally) and rebased so should be good to go?

**Comment by thomasbiddle** [comment]
I am attempting to have a Lambda deployed in `us-east-` to run it's policy against all regions. How can I achieve this?

    mode:
      execution-options:
        region: all

Does not work; yet the syntax when running from the command line appears to be like so: http://www.capitalone.io/docs/quickstart/advanced.html#running-against-multiple-regions

**Pull request merged**
