### PR TITLE
Prevent runtime mismatch

### PR DESCRIPTION
**Pull request by whit537**
Follow-on from discussion at https://github.com/capitalone/cloud-custodian/pull/1420#discussion_r128206725, ~~includes #1545~~.

### CODE REVIEW

**Comment by whit537** [comment]
Not sure where Travis (and therefore Coverage) are, but this is otherwise ready for review @kapilt.

**Comment by whit537** [comment]
Got Travis back. It's red for py36, investigating ...

**Comment by whit537** [comment]
Rebased and squashed with a new `placebo_data.zip`, was cd59afaf55512bc7025f8a90c52bc0e67146b6da.

**Comment by whit537** [comment]
This is green and ready for review.

**Comment by whit537** [comment]
Rebased, was 5ad9345921c6264ee7ab7402942a6da7a53a6db8.

**Comment by kapilt** [comment]
i'm a bit wary of doing implicit deltas, as its common to have multiple actors potentially running custodian, and doing an implicit delta on their execution env feels quite dangerous, albeit this effectively raises an error. But for example how would i upgrade the lambda policies from 2.7 to 3.6 with this in play? afaics the only reason we care is if there's compiled resources in the lambda (afaik none of the custodian policy lambdas need that).

**Comment by whit537** [comment]
> afaics the only reason we care is if there's compiled resources in the lambda (afaik none of the custodian policy lambdas need that).

There are different strategies for porting code from Python 2 to 3. We are using a [single-codebase](http://python3porting.com/strategies.html#python-2-and-python-3-without-conversion) strategy, but some other projects use a [split-codebase](http://python3porting.com/strategies.html#separate-branches-for-python-2-and-python-3) strategy. In general the single-codebase approach (ours) won out in the community, but there _are_ still projects with split codebases.

PyYAML has a [split codebase](https://github.com/yaml/pyyaml/blob/3.11/setup.py#L329) (though see [`ruamel.yaml`](http://yaml.readthedocs.io/en/latest/pyyaml.html#py2-py3-reintegration)). Core Custodian doesn't require PyYAML, but the mailer [does](https://github.com/capitalone/cloud-custodian/blob/1daaec83624f473ad45bfb3fd395817b23b09b4d/tools/c7n_mailer/requirements.txt#L15), which gives rise to [a broken mailer](https://github.com/whit537/cloud-custodian/pull/37#issuecomment-325610163) when specifying a remote runtime different from the local runtime, since we end up bundling the wrong version of PyYAML.

**Comment by whit537** [comment]
> how would i upgrade the lambda policies from 2.7 to 3.6 with this in play

Delete the old lambda and republish the new one? This only throws an error when local and remote differ. If there is no remote then create works fine.

**Comment by whit537** [comment]
If you want explicit runtime configuration then we could also throw an error on create, i.e. check locally for runtime match between config and environ before we even ping remote.

**Comment by whit537** [comment]
Or at least a warning?

**Comment by whit537** [comment]
I lied. Core Custodian _does_ require PyYAML, though we don't bundle it in `custodian_archive`.

https://github.com/capitalone/cloud-custodian/blob/1daaec83624f473ad45bfb3fd395817b23b09b4d/requirements.txt#L6

https://github.com/capitalone/cloud-custodian/blob/1daaec83624f473ad45bfb3fd395817b23b09b4d/c7n/mu.py#L198-L200

**Comment by whit537** [comment]
What about a devexp as follows?

```
$ custodian run policy.yml
Runtime mismatch! Policy specifies python3.6, your local is python2.7. Proceed? (y/n) n
$ custodian run policy.yml --ignore-runtime-mismatch
$
```

Probably in the mailer we'd stick with a hard-fail since we know it matters there?

**Comment by whit537** [comment]
Could even perhaps add an `allow_runtime_mismatch` key to policy config next to `runtime`?

**Comment by whit537** [comment]
@kapilt on call:

> We have three sources of truth:
>
>- config file
>- local environ
>- remote lambda
>
>We need to look at config.
>
>When we're not actually updating code ... we don't even care.

**Comment by whit537** [comment]
Alternate strategy in https://github.com/capitalone/cloud-custodian/pull/1611 ... *always* use `python3.6`.

**Comment by whit537** [comment]
Closing, will try a workaround in the mailer.

**Pull request closed without merging**
