### PR TITLE
ec2 set instance profile action bug fix for extant role replacement

### LINKED ISSUE #2601: EC2 Instance Profile  - Association and disassociation issue
As per the C7N _**set-instance-profile**_ is used to attach an IAM instance profile to an running or stopped EC2 instance. However, currently this action errors out if the instance already has an IAM role attached. It would be good to have a capability to replace current instance role with a new one (_**ReplaceIamInstanceProfileAssociation**_). The use case is, if the instance is wrongly assigned role custodian can check and correct it.

### PR DESCRIPTION
**Pull request by kapilt**
fixes #2601, also reduce api call count for role/profile association id discovery.

### CODE REVIEW

**Comment by thisisshi** [comment]
lgtm

**Comment by thisisshi** [comment]
Actually one more thing-- slightly unrelated but `valid_origin_states` should also include the instance state `stopped`, this was brought up in gitter a while back and I was waiting on a pr from a community member but it never came, might as well fix it up in this pr.

docs: https://docs.aws.amazon.com/cli/latest/reference/ec2/associate-iam-instance-profile.html

> Associates an IAM instance profile with a running or stopped instance

**Comment by kapilt** [comment]
Nice catch, thanks

**Comment by mukavik** [comment]
Thanks Kapilt. Do i need to reinstall C7N to get this working?

**Comment by kapilt** [comment]
yeah.. probably, it depends on how you've installed. if you did python setup.py install then you'll need to reinstall, python setup.py develop allows you to just update git. if you installed via pypi, you'll need to wait till we cut a new release (imminent over the next few days).

**Comment by mukavik** [comment]
I did pip install C7N.

**Comment by mukavik** [comment]
@kapilt just checking back to see if we have an ETA on the next new release that would include this fix. Thanks

**Pull request merged**
