### PR TITLE
Azure - Refactor NSG parameter names in code and in docs

### PR DESCRIPTION
**Pull request by tbarlow12**

### CODE REVIEW

**Comment by tbarlow12** [comment]
Forgot to change the name in the tests. pushing that soon

**Comment by tbarlow12** [comment]
this addresses issue #2541

**Comment by stefangordon** [comment]
cool tx, I'm still confused why the field names start with a capital letter, it seems wrong, but I see you mirrored what the aws VPC one does.  Will ping @kapilt and inquire why these are pascal case and not camel case - if it is a bug there i'd be inclined to make ours correct (even though we wouldn't want to take a breaking change on their schema).

**Comment by tbarlow12** [comment]
@stefangordon makes sense. would you like to see something like `except_ports`, `from_port` and names of that nature?

**Comment by stefangordon** [comment]
They should be camelcase, `exceptPorts, fromPort`  - but it is weird AWS one is an exception here so I'll wait to find out if I'm missing something :)

**Comment by stefangordon** [comment]
Ok looks like in that case AWS had some of these fields in the SDK already so they went with it - but I think we should do it correctly since we don't have that scenario and it is hard to change it once people start using it.  Everything in schema should be camelCase.

**Comment by stefangordon** [comment]
👍 👍  Just flake8 fix and good to go

**Comment by stefangordon** [comment]
Hmm, this is at least the third time I've seen the Tags tests cause an intermittent travis failure - I am suspicious something is wrong there.

**Pull request closed without merging**
