### PR TITLE
Fix bug when multiple S3 policy statements are similar

### PR DESCRIPTION
**Pull request by blt04**
This fixes a bug in the `has-statement` s3 filter when a bucket policy has multiple similar statements.  The solution is to stop looking for required_statements once it has been found.

For example, a bucket policy like:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "StatementOne",
            "Effect": "Allow",
            "Principal": "*",
            "Action": "s3:PutObject",
            "Condition": {
                "StringEquals": {
                    "s3:x-amz-acl": [
                        "public-read"
                    ]
                }
            }
            "Resource": "arn:aws:s3:::my-bucket/*"
        },
        {
            "Sid": "StatementTwo",
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::111122223333:root"
            },
            "Action": "s3:PutObject",
            "Resource": "arn:aws:s3:::my-bucket/*"
        }
    ]
}
```

paired with an policy like:

```
policies:
  - name: s3-public-bucket-policy
    resource: s3
    filters:
      - type: has-statement
        statements:
          - Effect: Allow
            Action: 's3:PutObject'
```

caused c7n to fail with an error like:
`ValueError: list.remove(x): x not in list`

### CODE REVIEW

**Comment by kapilt** [comment]
thanks for the pr, definitely want to add a unit test for this one.

**Comment by blt04** [comment]
Thanks for the review.  I added a test that fails without this fix and passes with it.

**Comment by kapilt** [comment]
thanks, lgtm, with one caveat, can you put a dummy account id instead of a real one, or use the one we use for testing recording.

**Comment by blt04** [comment]
I switched to using the test account.

**Pull request merged**
