### PR TITLE
Make tests portable across nosetests and py.test

### PR DESCRIPTION
**Pull request by whit537**
Pre-req for #903.

### CODE REVIEW

**Comment by whit537** [comment]
Ready for review, @kapilt.

**Comment by kapilt** [comment]
lgtm! thanks, looking forward to this. one note, i need to resurrect the computer i had drone secrets setup to do the prs w/ drone.yml changes, as drone will fail builds on checksum mismatch.

**Comment by kapilt** [comment]
looks like this does make tests 25% slower. given that, can you move the raises stuff to portable syntax (assertRaises) so we can switch interchangeable for now

```
$ time make test
AWS_ACCESS_KEY_ID=foo AWS_SECRET_ACCESS_KEY=bar AWS_DEFAULT_REGION=us-east-1 nosetests  --processes=-1 tests
...............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
----------------------------------------------------------------------
Ran 543 tests in 12.816s

OK

real    0m13.664s
user    1m17.970s
sys     0m6.204s
(custodian) :custodian me$ time py.test -n auto tests/
============================================================================================================ test session starts =============================================================================================================
platform darwin -- Python 2.7.13, pytest-3.0.6, py-1.4.32, pluggy-0.4.0
rootdir: /Users/me/projects/custodian, inifile: 
plugins: xdist-1.15.0
gw0 [543] / gw1 [543] / gw2 [543] / gw3 [543] / gw4 [543] / gw5 [543] / gw6 [543] / gw7 [543]
scheduling tests via LoadScheduling
...............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
======================================================================================================== 543 passed in 16.00 seconds =========================================================================================================

real    0m16.361s
user    1m47.995s
sys     0m10.193s
```

**Comment by whit537** [comment]
> can you move the raises stuff to portable syntax 

Done in 8d6a1434c4abd682943ffd9f5d28f6deff615ac6.

**Pull request merged**
