### PR TITLE
Add Python 3.6 to the test matrix at Travis

### PR DESCRIPTION
**Pull request by whit537**
Part of #705, includes #1214 (rebase once that's landed).

### CODE REVIEW

**Comment by kapilt** [comment]
thoughts on tox over hardcoding to a build sys

**Comment by whit537** [comment]
Per call and 65fae29d9da94bb84afdc062f5c2c067c4a85893 this is using tox under the hood with light touch at Travis (adds dep on [tox-travis](https://github.com/ryanhiebert/tox-travis), seems viable).

**Comment by whit537** [comment]
Rebased, was 65fae29d9da94bb84afdc062f5c2c067c4a85893.

**Comment by whit537** [comment]
Rebased, was 056634ddcadf233fd28f42eb8f216414005761f7.

**Comment by kapilt** [comment]
one more rebase pls, to get a clean diff with #1214 merged.

**Comment by whit537** [comment]
Done, was 8be6159a37d1f9bf6e2da9627ccbf9e163bb65ac.

**Comment by whit537** [comment]
Blorg. Rebased again on lastest master, and now Coveralls is failing with "Coverage decreased (-0.5%) to 89.6%."

**Comment by whit537** [comment]
The Coveralls base changed drastically, and I haven't yet sorted out why. The problem isn't on this PR, though ...

**Comment by whit537** [comment]
Travis [saw](https://travis-ci.org/capitalone/cloud-custodian/jobs/243438744#L830-L862) 12,000 lines of code but Coveralls [thinks](https://coveralls.io/jobs/26791445) Travis only saw 9,000. Game of telephone between Travis and Coveralls?

¯\\\_(ツ)\_/¯

**Comment by whit537** [comment]
Ftr, decided in private slack to merge #1293 and see if Coveralls recovers. [Seems to have](https://coveralls.io/builds/12001840)!

**Pull request merged**
