### PR TITLE
#309 RDS snapshot identifier

### PR DESCRIPTION
**Pull request by jeffastorey**
adding timestamp to the db identifier

### CODE REVIEW

**Comment by ewbankkit** [comment]
What about appending the same timestamp to the name of the snapshot created by the `snapshot` action?
* https://github.com/jeffastorey/cloud-custodian/blob/aba41a03062012a7c36860bc929254bc26ba06f4/c7n/resources/rds.py#L309

**Comment by ewbankkit** [comment]
Fixes #309.

**Comment by kapilt** [comment]
that sounds good, i think we should timestamp both, but with final on one form, we need to be able to unambiguously parse on the way out.

**Comment by ewbankkit** [comment]
There's prior art with the Redshift final snapshot:
* https://github.com/capitalone/cloud-custodian/blob/master/c7n/resources/redshift.py#L107

I suggest sticking to a consistent naming convention.

**Comment by jeffastorey** [comment]
updated and rebased

**Comment by kapilt** [comment]
merged kits which made this one fall out.. (squash is kinda of annoying with extant pull)

lgtm

**Pull request merged**
