### PR TITLE
#515 Resource Filter Fix

### PR DESCRIPTION
**Pull request by joshuaroot**
param ‘resource_type’ was not being sent to function.

Added check to see if option ‘resource’ was defined & to process that
resource, otherwise, process full policy

### CODE REVIEW

**Comment by joshuaroot** [comment]
blah. too rushed. going through test (like i should have before submitting pr)

**Comment by joshuaroot** [comment]
unittests pass without issue, manual check without --resource does not run policy

**Comment by kapilt** [comment]
can you rebase/squash the commits here.

**Comment by kapilt** [comment]
https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

**Comment by kapilt** [comment]
so rather than merging master, its easier for clean history if you just rebase changes on master.

**Pull request merged**
