### PR TITLE
fix for regions bug

### PR DESCRIPTION
**Pull request by scotwk**
@kapilt - your fix handles 90% of the problem services, but for some reason boto still reports no regions for a few services.  the list resources that this includes are:

['account', 'distribution', 'healthcheck', 'hostedzone', 'iam-certificate', 'iam-group', 'iam-policy', 'iam-profile', 'iam-role', 'iam-user', 'rrset', 'streaming-distribution', 'waf']

You can see the problem like so:

```
session.get_available_regions('iam')
[]
```

So I re-added in the code that skips the region validity test if the region list is empty.  And I added in the test that checks that ensures we can load a policy for each of the resources we support.

### CODE REVIEW

**Comment by kapilt** [comment]
'account' need special handling, the rest are singleton/global endpoints, they should not be expanded into separate policies, they should get a single region handling on 'all'.

**Comment by kapilt** [comment]
my previous fix I believe defaulted them to us-east-1 endpoint as a region which should suffice to make them global endpoint targeted. so wondering about the pr, stuck on a plane atm though.

**Comment by kapilt** [comment]
this still leaves a bad behavior of checking for global endpoint resources in each region, instead of once.

**Comment by scotwk** [comment]
@kapilt 

> 'account' need special handling, the rest are singleton/global endpoints, they should not be expanded into separate policies, they should get a single region handling on 'all'.

The fix on line 89 is specifically for `account`, or else you'll get a `KeyError trying to load any `account` policy.

```  
<snip>
File "/Users/kkronenfeld/sixfeetup/cloud-custodian/c7n/policy.py", line 89, in __init__
    resource_service_map[p['resource']], ())
KeyError: 'account'
```

As for the remaining ones, I did not change how you expand them when 'all' is supplied.  The problem is that botocore returns no available regions for them.  So when it does the check, `available_regions` is an empty list and therefore it ignores every single IAM policy (as well as the other problem resources in that list).

> this still leaves a bad behavior of checking for global endpoint resources in each region, instead of once.

You are right.  But the problem currently on the master branch is worse.  You cannot run a policy for any of those global endpoint resources.  Maybe the right solution is that when `available_regions` is empty it should be set to `[us-east-1]`?

**Comment by scotwk** [comment]
@kapilt - just saw your PR that handles this.  Reviewing that and closing this

**Pull request closed without merging**
