### PR TITLE
added docstring & example to iam.py

### PR DESCRIPTION
**Pull request by joshuaroot**
* added policy examples
* added docstring

### CODE REVIEW

**Comment by kapilt** [comment]
merge conflict, please merge trunk and resolve conflict.

**Comment by joshuaroot** [comment]
the documented filters have been tested & validated

some of the filters can/should be cleaned up a little more (no reason for used/unused filters when a boolean addition can simplify down to 1). 

also noticed that the remove-keys action doesn't seem to work.

i can do that in a separate pr

**Comment by kapilt** [comment]
the issue is that once something is in the publicly exposed interface it creates migration problems for extant users, exposed interfaces require careful thought and consideration... most of the ones your noting here are the ones you added.

**Comment by kapilt** [comment]
added in #775 for defining a policy and mechanism to clean up up bad/obsolete filters/actions

**Comment by joshuaroot** [comment]
the docstrings in here (at least for now) are valid

**Comment by joshuaroot** [comment]
PR is badly out of sync. Closing this PR & will open a new one as it will probably be faster once other changes are merged.

**Pull request closed without merging**
