### PR TITLE
Implement `c7n-sentry deploy`

### LINKED ISSUE #738: sentry log relay as lambda function
The sentry logger in c7n_sentry has some logic to work as a log subscription filter, but thats not completed. The goal would be to attach it as a long subscription filter to all log groups given a prefix.

### PR DESCRIPTION
**Pull request by whit537**
Closes #738. Includes #852 (will rebase if/when that lands before this is ready).

### CODE REVIEW

**Comment by whit537** [comment]
I've created the lambda using get_function, I see it in the console w/ no trigger now ... but still the same `KeyError` on `event['awslogs']` as at https://github.com/capitalone/cloud-custodian/issues/738#issuecomment-273770074.

**Comment by whit537** [comment]
Alright, I think those were holdovers from previous lambda deployments. Now that we're using LogSubscription instead of Events, I think we won't expect _any_ logs from `cloud-custodian-sentry` unless we log an exception from `custodian-bar`.

**Comment by whit537** [comment]
Where does `cloud-custodian-sentry` get its logs from? How is the configured?

**Comment by whit537** [comment]
I don't find UI in the console to see the arn of a log group (required by mu), guessing based on [these docs](http://docs.aws.amazon.com/cli/latest/reference/logs/describe-log-groups.html#examples) ....

**Comment by whit537** [comment]
Progress!

```
(cloud-custodian) $ c7n-sentry deploy -c config.json --region=us-west-2
2017-01-20 09:09:11,758: custodian.lambda:INFO Creating subscription filter for /aws/lambda/custodian-bar
Traceback (most recent call last):
  File "/Users/whit537/workbench/capitalone/cloud-custodian/bin/c7n-sentry", line 11, in <module>
    load_entry_point('c7n-sentry', 'console_scripts', 'c7n-sentry')()
  File "/Users/whit537/workbench/capitalone/cloud-custodian/tools/c7n_sentry/c7n_sentry/c7nsentry.py", line 509, in main
    options.command(options)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/tools/c7n_sentry/c7n_sentry/c7nsentry.py", line 468, in deploy
    manager.publish(func)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/c7n/mu.py", line 249, in publish
    if e.add(func):
  File "/Users/whit537/workbench/capitalone/cloud-custodian/c7n/mu.py", line 970, in add
    destinationArn=func.alias or func.arn)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/lib/python2.7/site-packages/botocore/client.py", line 251, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/lib/python2.7/site-packages/botocore/client.py", line 537, in _make_api_call
    raise ClientError(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidParameterException) when calling the PutSubscriptionFilter operation: Could not execute the lambda function. Make sure you have given CloudWatch Logs permission to execute your function.
(cloud-custodian) $
```

**Comment by whit537** [comment]
```diff
diff --git a/c7n/mu.py b/c7n/mu.py
index 4525e30..1b6581e 100644
--- a/c7n/mu.py
+++ b/c7n/mu.py
@@ -960,6 +960,7 @@ class CloudWatchLogSubscription(object):
                 # iam eventual consistency and propagation
                 time.sleep(self.iam_delay)
             except ClientError as e:
+                log.exception(e)
                 if e.response['Error']['Code'] != 'ResourceConflictException':
                     raise
             # Consistent put semantics / ie no op if extant
diff --git a/tools/c7n_sentry/c7n_sentry/c7nsentry.py b/tools/c7n_sentry/c7n_sentry/c7nsentry.py
index b98786e..890aff8 100644
--- a/tools/c7n_sentry/c7n_sentry/c7nsentry.py
+++ b/tools/c7n_sentry/c7n_sentry/c7nsentry.py
@@ -456,7 +456,10 @@ def deploy(options):
         name='cloud-custodian-sentry',
         handler='handler.process_log_event',
         role='arn:aws:iam::644160558196:role/custodian-mu',
-        log_groups=[],
+        log_groups=[{
+            'logGroupName': '/aws/lambda/custodian-bar',
+            'arn': 'arn:aws:logs:us-west-2:644160558196:log-group::*'
+        }],
         project=None,
         account_name=None,
         account_id=None
```

```
(cloud-custodian) $ c7n-sentry deploy -c config.json --region=us-west-2
2017-01-20 09:20:09,172: custodian.lambda:INFO Creating subscription filter for /aws/lambda/custodian-bar
2017-01-20 09:20:09,623: custodian.lambda:ERROR An error occurred (ResourceConflictException) when calling the AddPermission operation: The statement id (aws-lambda-custodian-bar) provided already exists. Please provide a new statement id, or remove the existing statement.
Traceback (most recent call last):
  File "/Users/whit537/workbench/capitalone/cloud-custodian/c7n/mu.py", line 958, in add
    Principal='logs.%s.amazonaws.com' % region)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/lib/python2.7/site-packages/botocore/client.py", line 251, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/lib/python2.7/site-packages/botocore/client.py", line 537, in _make_api_call
    raise ClientError(parsed_response, operation_name)
ClientError: An error occurred (ResourceConflictException) when calling the AddPermission operation: The statement id (aws-lambda-custodian-bar) provided already exists. Please provide a new statement id, or remove the existing statement.
Traceback (most recent call last):
  File "/Users/whit537/workbench/capitalone/cloud-custodian/bin/c7n-sentry", line 11, in <module>
    load_entry_point('c7n-sentry', 'console_scripts', 'c7n-sentry')()
  File "/Users/whit537/workbench/capitalone/cloud-custodian/tools/c7n_sentry/c7n_sentry/c7nsentry.py", line 509, in main
    options.command(options)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/tools/c7n_sentry/c7n_sentry/c7nsentry.py", line 468, in deploy
    manager.publish(func)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/c7n/mu.py", line 249, in publish
    if e.add(func):
  File "/Users/whit537/workbench/capitalone/cloud-custodian/c7n/mu.py", line 971, in add
    destinationArn=func.alias or func.arn)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/lib/python2.7/site-packages/botocore/client.py", line 251, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/lib/python2.7/site-packages/botocore/client.py", line 537, in _make_api_call
    raise ClientError(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidParameterException) when calling the PutSubscriptionFilter operation: Could not execute the lambda function. Make sure you have given CloudWatch Logs permission to execute your function.
```

**Comment by whit537** [comment]
Maybe we have an old permission stuck in there that needs to be cleared out?

**Comment by whit537** [comment]
[Sounds like](http://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements.html) statements are part of policies, but I don't find any policies (available to me?).

screen shot 2017-01-20 at 9 26 18 am

**Comment by whit537** [comment]
Where else might that statement be hiding? Somewhere under the `custodian-bar` Lambda?

**Comment by whit537** [comment]
Nothing suggestive on the advanced settings of the `custodian-bar` lambda.

**Comment by whit537** [comment]
https://docs.aws.amazon.com/lambda/latest/dg/intro-permission-model.html#intro-permission-model-access-policy

**Comment by kapilt** [comment]
that should be in mu.py in the log subscription filter event

**Comment by whit537** [comment]
Yes, that is where the error is coming from (once I [enabled logging](https://github.com/capitalone/cloud-custodian/pull/861#issuecomment-274082994)). But what does it mean and how do I fix it?

**Comment by whit537** [comment]
I mean, apparently we think it's okay to ignore the `ResourceConflictException`, so that the error I should focus on is the `InvalidParameterException`:

> Could not execute the lambda function. Make sure you have given CloudWatch Logs permission to execute your function.

**Comment by whit537** [comment]
I don't find a UI to view Lambda resource policies, so I guess I use the API:

```
(cloud-custodian) $ c7n-sentry deploy -c config.json --region=us-west-2
2017-01-21 05:44:16,096: custodian.lambda:INFO Creating subscription filter for /aws/lambda/custodian-bar
> /Users/whit537/workbench/capitalone/cloud-custodian/c7n/mu.py(965)add()
-> if e.response['Error']['Code'] != 'ResourceConflictException':
(Pdb) extant
{u'Policy': u'{"Version":"2012-10-17","Id":"default","Statement":[{"Sid":"aws-lambda-custodian-bar","Effect":"Allow","Principal":{"Service":"logs.us-west-2.amazonaws.com"},"Action":"lambda:InvokeFunction","Resource":"arn:aws:lambda:us-west-2:644160558196:function:cloud-custodian-sentry","Condition":{"ArnLike":{"AWS:SourceArn":"arn:aws:logs:us-west-2:644160558196:log-group::*"}}}]}', 'ResponseMetadata': {'RetryAttempts': 0, 'HTTPStatusCode': 200, 'RequestId': '8e4e8d80-dfc6-11e6-a24f-b522455ea1d2', 'HTTPHeaders': {'date': 'Sat, 21 Jan 2017 10:44:16 GMT', 'x-amzn-requestid': '8e4e8d80-dfc6-11e6-a24f-b522455ea1d2', 'content-length': '422', 'content-type': 'application/json', 'connection': 'keep-alive'}}}
(Pdb) pp extant
{u'Policy': u'{"Version":"2012-10-17","Id":"default","Statement":[{"Sid":"aws-lambda-custodian-bar","Effect":"Allow","Principal":{"Service":"logs.us-west-2.amazonaws.com"},"Action":"lambda:InvokeFunction","Resource":"arn:aws:lambda:us-west-2:644160558196:function:cloud-custodian-sentry","Condition":{"ArnLike":{"AWS:SourceArn":"arn:aws:logs:us-west-2:644160558196:log-group::*"}}}]}',
 'ResponseMetadata': {'HTTPHeaders': {'connection': 'keep-alive',
                                      'content-length': '422',
                                      'content-type': 'application/json',
                                      'date': 'Sat, 21 Jan 2017 10:44:16 GMT',
                                      'x-amzn-requestid': '8e4e8d80-dfc6-11e6-a24f-b522455ea1d2'},
                      'HTTPStatusCode': 200,
                      'RequestId': '8e4e8d80-dfc6-11e6-a24f-b522455ea1d2',
                      'RetryAttempts': 0}}
(Pdb)
```

```diff
diff --git a/c7n/mu.py b/c7n/mu.py
index 4525e30..4b5302e 100644
--- a/c7n/mu.py
+++ b/c7n/mu.py
@@ -960,6 +960,8 @@ class CloudWatchLogSubscription(object):
                 # iam eventual consistency and propagation
                 time.sleep(self.iam_delay)
             except ClientError as e:
+                extant = lambda_client.get_policy(FunctionName=func.name)
+                import pdb; pdb.set_trace()
                 if e.response['Error']['Code'] != 'ResourceConflictException':
                     raise
             # Consistent put semantics / ie no op if extant
diff --git a/tools/c7n_sentry/c7n_sentry/c7nsentry.py b/tools/c7n_sentry/c7n_sentry/c7nsentry.py
index b98786e..890aff8 100644
--- a/tools/c7n_sentry/c7n_sentry/c7nsentry.py
+++ b/tools/c7n_sentry/c7n_sentry/c7nsentry.py
@@ -456,7 +456,10 @@ def deploy(options):
         name='cloud-custodian-sentry',
         handler='handler.process_log_event',
         role='arn:aws:iam::644160558196:role/custodian-mu',
-        log_groups=[],
+        log_groups=[{
+            'logGroupName': '/aws/lambda/custodian-bar',
+            'arn': 'arn:aws:logs:us-west-2:644160558196:log-group::*'
+        }],
         project=None,
         account_name=None,
         account_id=None
```

**Comment by whit537** [comment]
JSON-decoded:

```
(Pdb) pp policy
{u'Id': u'default',
 u'Statement': [{u'Action': u'lambda:InvokeFunction',
                 u'Condition': {u'ArnLike': {u'AWS:SourceArn': u'arn:aws:logs:us-west-2:644160558196:log-group::*'}},
                 u'Effect': u'Allow',
                 u'Principal': {u'Service': u'logs.us-west-2.amazonaws.com'},
                 u'Resource': u'arn:aws:lambda:us-west-2:644160558196:function:cloud-custodian-sentry',
                 u'Sid': u'aws-lambda-custodian-bar'}],
 u'Version': u'2012-10-17'}
(Pdb)
```

**Comment by whit537** [comment]
I don't see something in the policy that would vary such that it would cause the `InvalidParameterException`. Something else is going on ...

**Comment by whit537** [comment]
Like, what's the _effect_ of the policy?

**Comment by whit537** [comment]
Ah! I bet it's `SourceArn=group['arn']`.

**Comment by whit537** [comment]
So I'm [back](https://github.com/capitalone/cloud-custodian/pull/861#issuecomment-274080185) to needing to determine the ARN for a log group, which there appears to be no UI for.

**Comment by whit537** [comment]
Guessed and confirmed via API:

`arn:aws:logs:us-west-2:644160558196:log-group:/aws/lambda/custodian-bar:*`

**Comment by whit537** [comment]
```
(cloud-custodian) $ c7n-sentry deploy -c config.json --region=us-west-2
2017-01-21 06:49:15,806: custodian.lambda:INFO Creating subscription filter for /aws/lambda/custodian-bar
(cloud-custodian) $
```

**Comment by whit537** [comment]
We have logs!

screen shot 2017-01-21 at 7 03 39 am

**Comment by whit537** [comment]
That's `cloud-custodian-sentry` picking up a log event from `custodian-bar`. 👍

**Comment by whit537** [comment]
No error! Is it in Sentry!?

screen shot 2017-01-21 at 7 51 26 am

**Comment by whit537** [comment]
Yes! 💃 

screen shot 2017-01-21 at 7 53 20 am

**Comment by whit537** [comment]
Phew! Okay! The next step here is to unhardwire everything in 63ca909fd9f58f73ae3ba5b2281e2435d36e1f48.

**Comment by whit537** [comment]
A behavior I am seeing: I get an `InvalidParameterException` as [before](), but an immediate rerun succeeds:

```
(cloud-custodian) $ c7n-sentry deploy -c config.json --region=us-west-2
2017-01-23 04:21:16,897: custodian.lambda:INFO Creating subscription filter for /aws/lambda/custodian-bar
Traceback (most recent call last):
  File "/Users/whit537/workbench/capitalone/cloud-custodian/bin/c7n-sentry", line 11, in <module>
    load_entry_point('c7n-sentry', 'console_scripts', 'c7n-sentry')()
  File "/Users/whit537/workbench/capitalone/cloud-custodian/tools/c7n_sentry/c7n_sentry/c7nsentry.py", line 504, in main
    options.command(options)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/tools/c7n_sentry/c7n_sentry/c7nsentry.py", line 461, in deploy
    manager.publish(func)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/c7n/mu.py", line 249, in publish
    if e.add(func):
  File "/Users/whit537/workbench/capitalone/cloud-custodian/c7n/mu.py", line 970, in add
    destinationArn=func.alias or func.arn)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/lib/python2.7/site-packages/botocore/client.py", line 251, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/lib/python2.7/site-packages/botocore/client.py", line 537, in _make_api_call
    raise ClientError(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidParameterException) when calling the PutSubscriptionFilter operation: Could not execute the lambda function. Make sure you have given CloudWatch Logs permission to execute your function.
(cloud-custodian) $ c7n-sentry deploy -c config.json --region=us-west-2
2017-01-23 04:22:46,658: custodian.lambda:INFO Creating subscription filter for /aws/lambda/custodian-bar
(cloud-custodian) $ 
```

**Comment by whit537** [comment]
Alright, so I'm looking at how to utilize the [`orgreplay`](https://github.com/whit537/cloud-custodian/blob/63ca909fd9f58f73ae3ba5b2281e2435d36e1f48/tools/c7n_sentry/c7n_sentry/c7nsentry.py#L365-L440) machinery with [`deploy`](https://github.com/whit537/cloud-custodian/blob/63ca909fd9f58f73ae3ba5b2281e2435d36e1f48/tools/c7n_sentry/c7n_sentry/c7nsentry.py#L443-L461), because presumably we want the same extraction of account into from `config.json`? And the same auto-creation of teams and projects?

**Comment by whit537** [comment]
What's up with calling `process_log_group` twice?

**Comment by whit537** [comment]
Hub and spoke.

**Comment by whit537** [comment]
Rebased and squashed. Was e7465e10df580f8137922af382d7fefbb41d8535.

**Comment by whit537** [comment]
Ready for review, @kapilt! :-)

**Pull request merged**
