### PR TITLE
Adding tox to requiremvents-dev.txt

### PR DESCRIPTION
**Pull request by scotwk**
tox was missing from the requirements and I had to manually install it

### CODE REVIEW

**Comment by whit537** [comment]
You're supposed to install tox globally. It creates virtualenvs for you, one for each `testenv:*` defined in [`tox.ini`](https://github.com/capitalone/cloud-custodian/blob/454a5bf092794b2f4214adfa075d55079175a569/tox.ini).

**Comment by scotwk** [comment]
> You're supposed to install tox globally. It creates virtualenvs for you, one for each testenv:* defined in tox.ini.

@whit537 - should that be documented in either of these pages?

http://www.capitalone.io/cloud-custodian/docs/developer/installing.html
http://www.capitalone.io/cloud-custodian/docs/developer/tests.html

**Comment by whit537** [comment]
@scotwk It did get added there in #1303, but that's not deployed yet for whatever reason.

**Comment by scotwk** [comment]
@whit537 - great - I see it locally in my repo.  (Should have checked there first)

**Comment by whit537** [comment]
@scotwk No worries, sounds like we're fine having this in `requirements-dev.txt` anyway. :-)

**Pull request merged**
