### PR TITLE
rds and elb tag/remove-tag support, closes #150 and closes #149

### LINKED ISSUE #149: Support tagging RDS instances
When trying to add a tag to a RDS instance I get an error.

### LINKED ISSUE #150: Support tagging on ELB
When trying to add a tag to an ELB I get an error.

### PR DESCRIPTION
**Pull request by kapilt**
rds and elb tag/remove-tag support, closes #150 and closes #149

### CODE REVIEW

**Comment by awolde** [comment]
How do we use remove-tag and tag actions? Documentation is really poor.

**Comment by kumarsiyer** [comment]
go ahead and run custodian schema elb.actions.remove-tag this will give you the documentation required to remove-tags.

The schema usage can be used to retrieve documentation for any given custodian action or filter

**Comment by awolde** [comment]
`$ custodian schema rds.actions.remove-tag

Help
----
Remove tags from ec2 resources.

Schema
------

{   'additionalProperties': False,
    'properties': {   'tags': {   'items': {   'type': 'string'}, 'type': 'array'},
                      'type': {   'enum': ['untag', 'unmark', 'remove-tag']}},
    'required': ['type'],
    'type': 'object'}
`

Here is my yml
`policies:
  - name: add-rds-vpcname-tag
    resource: rds
    comment: adds vpcname tag
    query:
      - vpc-id: "vpc-xxxx"
    actions:
      - type: remove-tag
        items: 'Infrastructure'
`
I dont know how to translate that doc into usable yml file. Am I missing something?

**Comment by kumarsiyer** [comment]
try this ...

  - name: add-rds-vpcname-tag
    resource: rds
    comment: adds vpcname tag
    query:
      - vpc-id: "vpc-xxxx"
    actions:
      - type: remove-tag
        tags: ["tag_name"]

**Comment by awolde** [comment]
That worked! But the query is not working and the tagging is done across all vpc's. Filter does not have vpc schema for rds. Is there a way to filter by vpc for rds?

**Comment by tim-elliott** [comment]
The full condition could be something like (using filters instead of query):
    filters:
      - type: value
        key: "VpcId"
        op: in
        value: ["vpc-xxxx"]
    actions:
      - type: remove-tag
        tags: ["tag_name"]

**Comment by awolde** [comment]
Seems like this one worked. vpcid is under DBSubnetGroup hash.

```
    filters:
      - type: value
        key: "DBSubnetGroup.VpcId"
        value: "vpc-xxxx"
    actions:
      - type: tag
        tags: {'Environment': 'Production'}
```

**Pull request merged**
