### PR TITLE
Allow S3 output to work from Lambda Functions

### PR DESCRIPTION
**Pull request by jantman**
Right now, trying to send output to S3 from a Lambda function fails with a traceback because c7n.handler.Config [tries to blindly os.mkdir the output_dir](https://github.com/capitalone/cloud-custodian/blob/c2800f0185f684a2f8470b08fa4d0a88b0118d7b/c7n/handler.py#L73) if it doesn't exist, even if ``output_dir`` is an s3:// url, i.e.:

Policy snippet:
```yaml
    mode:
      type: periodic
      schedule: "rate(1 hour)"
      role: arn:aws:iam::xxxxxxxxxxxx:role/cloud-custodian-xxxxxxxxxxxx
      execution-options:
        log_group: /cloud-custodian/xxxxxxxxxxxx/us-east-1
        output_dir: s3://cloud-custodian-xxxxxxxxxxxx/logs
```

CloudWatch Logs snippet:
```
[Errno 2] No such file or directory: 's3://cloud-custodian-xxxxxxxxxxxx/logs': OSError
Traceback (most recent call last):
File "/var/task/custodian_policy.py", line 4, in run
return handler.dispatch_event(event, context)
File "/var/task/c7n/handler.py", line 99, in dispatch_event
options = Config.empty(**options_overrides)
File "/var/task/c7n/handler.py", line 74, in empty
os.mkdir(d['output_dir'])
OSError: [Errno 2] No such file or directory: 's3://cloud-custodian-xxxxxxxxxxxx/logs'
```

It appears that this code must be from before the existence of [c7n.outputs.FSOutput](http://www.capitalone.io/cloud-custodian/docs/generated/c7n.html#c7n.output.FSOutput) which abstracts all of that. Removing that one branch from the handler lets FSOutput take over, and do the right thing regardless of whether output_dir is S3 or a directory. I've run this branch in our AWS account, and it's now properly writing logs to S3.

### CODE REVIEW

**Comment by kapilt** [comment]
probably should do a conditional check here wrt to how the path starts, the original behavior here was working around a lambda issue that we encountered enough times over a long enough period to warrant a workaround, different executing user then previous in the same container, resulting in some permission issues on /tmp. simply doing a check on for `s3:` prefix or `/` should suffice.

**Comment by jantman** [comment]
@kapilt shouldn't [c7n.output.FSOutput.select](https://github.com/capitalone/cloud-custodian/blob/master/c7n/output.py#L160) determine that it's a filesystem path, and then [c7n.output.DirectoryOutput.__init__](https://github.com/capitalone/cloud-custodian/blob/master/c7n/output.py#L196) will create the directories?

There's still a call to ``os.makedirs`` on the output path, it's just happening a bit deeper down in the code, IMO where it _should_ happen (with the DirectoryOutput-specific code).

**Comment by jantman** [comment]
Unless maybe I'm missing something with the details of the Lambda bug?

**Comment by kapilt** [comment]
that makes sense, and sounds good.

**Comment by jantman** [comment]
Cool, thank you so much! I've updated with the latest master.

**Comment by kapilt** [comment]
closing in favor of the implementation in #1386 which was a bit more complete, thanks.

**Pull request closed without merging**
