### PR TITLE
Updating doc year to 2017, along with copyright headers

### PR DESCRIPTION
**Pull request by scotwk**
I updated the year in the documentation to 2017 (from 2016).  Also, I updated the copyright headers in the source code.  There were two styles that you have used in 2017:

```
# Copyright 2017 Capital One Services, LLC

# Copyright 2016-2017 Capital One Services, LLC
```

I updated all the instances of 2016 with the former, but if you prefer the latter I could switch to that.

### CODE REVIEW

**Comment by kapilt** [comment]
let me get some clarification on this, i would think it would be the later on extant files, but for  new files introduced in 2017 it would be the date of origination.

**Comment by kapilt** [comment]
@jaredsmith can you comment/ping when you have an update on std policy.

**Comment by kapilt** [comment]
okay guidance is anything with 2016 and has been updated this year to go to 2016-2017, and for anything new in 2017 to just have 2017.

**Comment by scotwk** [comment]
@kapilt - guidelines followed, although some files were created in 2015 so those say 2015-2017.  (Is that a problem?  If so it's an easy fix.)

Note that I added a new script at `tools/utils/update_headers.py`.  You can just run this script and it will automatically update any headers for you to the correct format, and also tell you about any files without headers.  This is useful when new contributions are added to ensure the correct copyright, or come January of a new year.

```
$ python update_headers.py 
Updating  ../../c7n/__init__.py
Updating  ../../c7n/actions.py
Updating  ../../c7n/cache.py
Updating  ../../c7n/cli.py
Updating  ../../c7n/commands.py
Updating  ../../c7n/credentials.py
...
```

It's not that polished since I didn't want to take too long on it (e.g. it only looks at the first line and does not work if a shebang line is present) but I can fix up the last few things if you think it's worthwhile.

**Pull request merged**
