### PR TITLE
--vars flag for variable substitution

### PR DESCRIPTION
**Pull request by scotwk**
Allow a variables file to be passed in in YAML syntax.

Currently does substitution using Python's str.format syntax.

Issue #938

### CODE REVIEW

**Comment by scotwk** [comment]
@kapilt - here is an example policy:

```
policies:
- name: ec2-running-instances
  resource: {resource}
  comment: |
    Report all running instances
  filters:
    - not:
      - InstanceId: i-036ee05e8c2ca83b3
```

and vars file (in yaml):

```
- resource: ec2
```

**Comment by kapilt** [comment]
lgtm re example

**Comment by ocampocj** [comment]
@scotwk - definitely lgtm, but would it be possible to use this functionality in conjunction with 'value_from'?  @kapilt - we'd talked a few weeks ago about the possibility of pulling variables from json data...

**Comment by ocampocj** [comment]
@kapilt - I spoke to @scotwk this morning and I think we have ironed out what I'd like to do, from a policy perspective:

`vars:
  account_contacts: &accounts_contacts s3://bucket/contacts.json

policies:
  - name: enterprise-ec2-age
    resource: ec2
    filters:
      - age: 30
      - type: instance-age
        days: 30
        op: gt
    actions:
    - type: notify
      to: 
        value_from:
        url: *account_contacts
        expr: accounts.{ account }.account_owner*
      from:
      transport:
        type: sqs
        queue: https://blah.aws.com`

@kapilt - { account } would have to become some sort of built in variable that is interpreted by Custodian.  I think the 'value_from' functionality in the notify could end up being a separate pull request...  Any comments on the implementation of that?

**Comment by scotwk** [comment]
write tests

**Comment by scotwk** [comment]
@kapilt - Tests are added.  This one is good to go in phase 1.  Let's chat about future phases (Chris' requests) when you have time.

**Comment by ocampocj** [comment]
@scotwk and @kapilt - I'll try to get something setup to discuss next week.

**Comment by scotwk** [comment]
@ocampocj - Let me know when.  I'll be traveling Tue - Thu so those days might not work for me.

**Comment by kapilt** [comment]
resolved on merge conflicts

**Comment by kapilt** [comment]
so i have some trepidations about the syntax, namely if we entrench pyformat string syntax, and later switch out to runtime variable interpolation we need to be compatible on the template interpolation syntax. i had notionally thought we might switch out to jinja2 if we went to runtime interpolation, but realizing now that is still significant overkill. i think we'll just carry forward on the pyformat for even for runtime interpolation.

**Comment by caversa** [comment]
I'm doing some experimentation with this new feature, which I'm very happy to see is in place!  I have had success passing variables in, which will now greatly simplify the number of files I need to maintain.  THANKS!  

One note though - I had been using the 'account' standard variable that is described in the mailer template as  the short name of the account within the subject.  I noticed that if I pass in the --vars the account is no longer translated to the short name (regardless of the variables I put into the vars file).  

      subject: Tagging Compliance Violation in {{ account }}

Is that conflicting now with this new feature?  I'll omit the account reference in the subject for now, since the ability of substituting queue names, etc. trumps the account short name in my subject line, but wanted to alert you of the issue.

Thanks,
Carrie

**Comment by scotwk** [comment]
@caversa - Hi Carrie.  I think you are referring to the email template that allows for substituting in a few special variables (such as account, recipient, policy, etc)?  This vars file work does not currently have any default variables, although they could be useful and we'll look into adding them in a subsequent iteration.

Note that the substitution should use syntax like this: `{account}` or `{resource}`

Let me know if you have further questions.

**Comment by caversa** [comment]
Hi Scott,

Yes, I was using the predefined account variable that is referenced in the https://github.com/capitalone/cloud-custodian/tree/master/tools/c7n_mailer in section 'Writing an email template'.  Even if the vars file is empty, the passing in of the parameter breaks the mailer account variable if it is referenced within the subject.  However, it does not appear to affect any of the mailer variables defined within the jinja template itself (i.e. account variable does get populated) so maybe it working via the subject earlier was just a 'nice to have' that I don't have any longer.   If in the future default variables to represent account number or region become available, I would certainly take advantage of that, as that is primarily what I'm needing to pass in to identify the queue (which is named exactly the same in each account, but we wanted to manage this in a distributed manner).

Thanks very much for this enhancement!

Carrie

**Comment by scotwk** [comment]
@caversa - hmmm, I haven't used the mailer before and I certainly didn't intend to break anything that was working before.  But I might understand why it is happening.  Can you share with me a policy that you have that is causing the subject substitution to break so I can test locally?

**Comment by caversa** [comment]
Here's an example.:

policies:
- name: test
  resource: ec2
  description:
    Test
  filters:
      - "tag:foo": absent
  actions:
    - type: notify
      template: default
      subject: TEST in {account}
      action_desc: "Test"
      to:
        - foo@bar.com
      transport:
        type: sqs
        queue: https://sqs.us-east-1.amazonaws.com/12345678/cloud-custodian-queue

**Comment by ocampocj** [comment]
@caversa - thanks for sharing this - it was definitely helpful.  @scotwk - it sounds like this issue was exactly what @kapilt was leading onto a few days ago:

"so i have some trepidations about the syntax, namely if we entrench pyformat string syntax, and later switch out to runtime variable interpolation we need to be compatible on the template interpolation syntax. i had notionally thought we might switch out to jinja2 if we went to runtime interpolation, but realizing now that is still significant overkill. i think we'll just carry forward on the pyformat for even for runtime interpolation."

We should probably discuss this next week.

**Comment by scotwk** [comment]
@ocampocj - I wasn't pushing for any particular syntax.  My initial PR used this just as a placeholder so that I could have all the other code, but it's easy to swap out for anything else (at policy load time.  At policy run time is a little harder because validation has to happen).  I talked briefly with Kapil at pycon about this and he had reservations about pulling in all of jinja2.

I haven't used the mailer before so I wasn't aware of this conflict.  I haven't had a chance to dig into it yet and test the policy @caversa supplied, but some initial thoughts:

First, I thought the mailer used double braces (i.e. `{{account}}`) so I was surprised by that policy.  Also, I thought they were separate j2 files, not embedded in the policy itself.

Second, the substitution does actually work if you have a vars file with `account: foo` in it.  I did a quick test of this earlier.

Third - and this is something you and I talked about awhile back - we should probably provide a few defaults such as `region`, `account` and `policy`.

**Comment by ocampocj** [comment]
@scotwk - the point about the double curly braces is a good one.  

@caversa - in your original comment above, you had double curly braces, but as @scotwk noted, the syntax for this new functionality specifies a single curly brace and you have a single brace in your example policy.  I can test this later myself, but maybe you can confirm the policy that you're seeing issues with (double or single braces)?

**Comment by caversa** [comment]
@ocampocj  Double or single curly braces without the vars flag translates correctly to the short account name.

When I pass in the vars flag: If I use single curly braces, I get an error if I haven't explicitly defined account in the vars file.  If I use double curly braces I do not get an error but I literally get {account} in my subject line.

**Comment by ocampocj** [comment]
Thanks for confirming @caversa - long term, there are some more variable-related features that @scotwk is already working on (as he noted above), which should resolve this.  For now, it looks like the interpretation of the existing mailer variables does overlap with this new functionality and they are not compatible, whether single or double braces are used.

**Comment by caversa** [comment]
That's fine.  Thanks guys!

**Comment by mtacker** [comment]
Hello @scotwk.  Related to the topic above, does CC support parameters in other resources such as EC2.  I am looking to parameterize account ID in my YAML file.  As in.

policies:
- name: Mark_untagged_instances
  mode:
      type: periodic
      schedule: "rate(1 hour)"
      role: "arn:aws:iam::{{ accountid }}:role/acct-managed/c7nlambda"
  resource: ec2
  description: |
    Marks improperly tagged instances with "maid_status" tag. (modify 'Schedule' to appropriate timing)
  filters:
    - State.Name: running
    - or:
      - "tag:Environment": absent
      - "tag:Application": absent
      - "tag:CreatorName": absent
      - "tag:TeamName": absent
    - "tag:maid_status": absent #This tag is required to prevent re-marking of previously marked instances
  actions:
    - type: mark-for-op
      op: stop
      days: 1

Thanks for any thoughts.  And great tool by the way!  This is good stuff.

**Comment by scotwk** [comment]
@mtacker - that was the goal of this PR, but it has been put on hold for higher priority work at the moment.  `account_id` and `region` would probably become variables that are automatically populated so you could do exactly what you are looking for.

**Pull request merged**
