### PR TITLE
Empty Key Name is valid for ASG Launch Configuration.

### PR DESCRIPTION
**Pull request by ewbankkit**
* Fixes https://github.com/capitalone/cloud-custodian/issues/267

### CODE REVIEW

**Comment by kapilt** [comment]
this needs an update? or was this included in the other pr?

**Comment by ewbankkit** [comment]
Just rebased with fix from https://github.com/capitalone/cloud-custodian/pull/266.

**Comment by kapilt** [comment]
doh.. one more time

**Comment by ewbankkit** [comment]
And rebased again, for the last time I hope.

**Pull request merged**
