### PR TITLE
cleaning test output

### PR DESCRIPTION
**Pull request by alfredgamulo**

### CODE REVIEW

**Comment by kapilt** [comment]
could you explain this a little more, those tests are explicitly capturing test output to a buffer for comparisons? if the capture logging test helper is persisting changes to global log level, then we should modify it to add a cleanup to restore the level.

**Comment by alfredgamulo** [comment]
I found that `test_encrypt_volumes` doesn't actually use the saved output

for `test_route53_hostedzone_tag_exception`, this is a test that I had written in a previous PR and I've learned since then that specifying `custodian.actions` as the logger to retrieve is sufficient for passing the test while also cleaning the testing output.

**Comment by kapilt** [comment]
yeah.. i'm seeing the issue your ran into, still debugging, there's seems to be a number of issues in the current test setup, i'm working on a few fixes.

**Comment by whit537** [comment]
> i'm working on a few fixes.

&rarr; #1326, might obviate this PR

**Comment by alfredgamulo** [comment]
@whit537 You're right.

**Pull request closed without merging**
