### PR TITLE
Add new actions to the account resource

### PR DESCRIPTION
**Pull request by skurfer**
Specifically, those described in #339 and #340.

One thing I wasn’t clear on: When calling `describe_configuration_recorders()` or `describe_trails()`, will you *ever* see results for an account other than the one you’ve logged into?

If not, we can probably drop the account ID checking loop in the Config actions. If so, we probably need to add a loop like that to the CloudTrail actions.

### CODE REVIEW

**Comment by kapilt** [comment]
hmm the goal for these was more about ensuring the trail was active and functional, i'm also more inclined to include config and trail in the name since that's common parlance where as record-start is ambigious.

**Comment by skurfer** [comment]
> hmm the goal for these was more about ensuring the trail was active and functional

Sorry to misinterpret. Those issues had nothing in their descriptions. 😕

So to clarify, when you say “ensuring the trail was active and functional”, do you mean the action should make sure the `check-cloudtrail` filter will match the trail?

> i'm also more inclined to include config and trail in the name since that's common parlance where as record-start is ambigious.

From the boto3 docs, “start recording” seemed like the only thing you could do to a Config that would resemble “enable”.

**Comment by kapilt** [comment]
yeah, my bad, it was intended to put the trail and recorder in place if it had been deleted, or to enable if it had been disabled. ie yes  it was more about making sure check-cloudtrail would match. 

re the record-start, on an account resource its a bit ambiguous what that means, its better there to qualify, if it was an actual trail or config resource it would be fine and unambiguous.

although i'm wondering if we just pull these into separate resources (cloudtrail and config-recorder respectively), we generally consider these primitives that require an account, but there's little to distinguish them from other resource types outside of primacy to security.

thoughts?

**Comment by skurfer** [comment]
> although i'm wondering if we just pull these into separate resources (cloudtrail and config-recorder respectively)

As it exists now, the resources passed to the `process()` method are accounts, which aren’t really what we’re operating on. It would be nice if it passed in trails or configs respectively. That’s the main argument I can think of in favor of separating them. Whether or not it’s worth the effort, I can’t say.

**Comment by kapilt** [comment]
for config recorders it seems questionable, afaik only one can be active. for trails its more useful due to their expanding feature scope (s3 data events) and allowed cardinality.

**Comment by kapilt** [comment]
i went ahead and added a separate cloudtrail resource.

**Pull request closed without merging**
